#**********************************************************************  
#	*주의 사항
#		현재 스크립트 파일은 파일명만 출력되어 있습니다.
#		따라서, 저장된 추출 결과 파일의 경로를 'read.table' 또는 'read.fwf'에 추가하여야 합니다.
#	예) 다운로드 받은 폴더명 : C:\Download
#	  ※ 파일 경로 추가 : "[다운로드 받은 폴더명]\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt"
# 		read.table("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#		또는
#		read.fwf("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#
#		R 스크립트는 R 에서 파일 경로만 수정하시면 바로 실행(Ctrl+Alt+R)가능하며,
#		데이터셋 생성 후에 R 의 여러 가지 분석 기능을 사용할 수 있습니다.
#
#**********************************************************************

install.packages("dplyr")
library(dplyr)

mdis <- read.table("1981_경제활동인구조사 연간자료1 (1981-1999)_20250711_01423.csv", header=FALSE, sep=",", colClasses = c("character"
, "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character"
, "character", "character", "character", "character", "character", "character", "character", "character", "character", "character"), skip=1, na.string=c("*","**","***","****","*****","******","*******","********","*********","**********","."))

        mdis$V3<- recode_factor(mdis$V3, '1'="가구주")
        mdis$V3<- recode_factor(mdis$V3, '2'="배우자")
        mdis$V3<- recode_factor(mdis$V3, '3'="미혼자녀")
        mdis$V3<- recode_factor(mdis$V3, '4'="기혼자녀 및 배우자, 그 자녀")
        mdis$V3<- recode_factor(mdis$V3, '5'="형제자매")
        mdis$V3<- recode_factor(mdis$V3, '6'="부모, 시부모, 장인장모")
        mdis$V3<- recode_factor(mdis$V3, '7'="조부모, 시조부모")
        mdis$V3<- recode_factor(mdis$V3, '8'="기타 친척")
        mdis$V3<- recode_factor(mdis$V3, '9'="동거인, 고용인, 식모, 하숙인")
        mdis$V4<- recode_factor(mdis$V4, '1'="남자")
        mdis$V4<- recode_factor(mdis$V4, '2'="여자")
        mdis$V7<- recode_factor(mdis$V7, '1'="미혼")
        mdis$V7<- recode_factor(mdis$V7, '2'="유배우")
        mdis$V7<- recode_factor(mdis$V7, '3'="사별")
        mdis$V7<- recode_factor(mdis$V7, '4'="이혼")
        mdis$V8<- recode_factor(mdis$V8, '1'="안다녔음(수학여부는 0)")
        mdis$V8<- recode_factor(mdis$V8, '2'="국민학교")
        mdis$V8<- recode_factor(mdis$V8, '3'="중학교")
        mdis$V8<- recode_factor(mdis$V8, '4'="인문고교")
        mdis$V8<- recode_factor(mdis$V8, '5'="실업고교")
        mdis$V8<- recode_factor(mdis$V8, '6'="초대및전문")
        mdis$V8<- recode_factor(mdis$V8, '7'="대학이상")
        mdis$V9<- recode_factor(mdis$V9, '1'="졸업")
        mdis$V9<- recode_factor(mdis$V9, '2'="재학")
        mdis$V9<- recode_factor(mdis$V9, '3'="중퇴")
        mdis$V10<- recode_factor(mdis$V10, '1'="일하였음&lt;20으로 로감&gt;")
        mdis$V10<- recode_factor(mdis$V10, '2'="직장은 있지만 일은 하지않았음")
        mdis$V10<- recode_factor(mdis$V10, '3'="직장또는 일거리를 구하고 있었음")
        mdis$V10<- recode_factor(mdis$V10, '4'="집안일(가사)을 돌보았음")
        mdis$V10<- recode_factor(mdis$V10, '5'="학교(원)에 다녔음")
        mdis$V10<- recode_factor(mdis$V10, '6'="연소 또는 연로")
        mdis$V10<- recode_factor(mdis$V10, '7'="아무것도 할 수 없었음")
        mdis$V10<- recode_factor(mdis$V10, '8'="기타()")
        mdis$V11<- recode_factor(mdis$V11, '1'="있었음&lt;20으로 로 감&gt;")
        mdis$V11<- recode_factor(mdis$V11, '2'="없었음")
        mdis$V12<- recode_factor(mdis$V12, '11'="일시적 병&lt;22번으로 감&gt;")
        mdis$V12<- recode_factor(mdis$V12, '12'="일기불순&lt;22번으로 감&gt;")
        mdis$V12<- recode_factor(mdis$V12, '13'="연가 또는 휴가&lt;22번으로 감&gt;")
        mdis$V12<- recode_factor(mdis$V12, '14'="노동쟁의&lt;22번으로 감&gt;")
        mdis$V12<- recode_factor(mdis$V12, '15'="조업중단&lt;22번으로 감&gt;")
        mdis$V12<- recode_factor(mdis$V12, '16'="조업중단(무급)&lt;10번으로 감&gt;")
        mdis$V12<- recode_factor(mdis$V12, '17'="자영업주로서 사업부진&lt;10번으로 감&gt;")
        mdis$V12<- recode_factor(mdis$V12, '18'="기타&lt;10번으로 감&gt;")
        mdis$V12<- recode_factor(mdis$V12, '20'="없었음&lt;10번으로 감&gt;")
        mdis$V13<- recode_factor(mdis$V13, '1'="구해보았음(12번이동)")
        mdis$V13<- recode_factor(mdis$V13, '2'="구해보지 않았음")
        mdis$V14<- recode_factor(mdis$V14, '11'="있었음-일시적 병")
        mdis$V14<- recode_factor(mdis$V14, '12'="있었음-일기불순")
        mdis$V14<- recode_factor(mdis$V14, '13'="있었음-직장대기 또는 구직결과 대기")
        mdis$V14<- recode_factor(mdis$V14, '14'="있었음-자영업 구상 및 준비")
        mdis$V14<- recode_factor(mdis$V14, '15'="있었음-기타()")
        mdis$V14<- recode_factor(mdis$V14, '20'="없었음&lt;16번으로 감&gt;")
        mdis$V15<- recode_factor(mdis$V15, '1'="직업소개소")
        mdis$V15<- recode_factor(mdis$V15, '2'="광고를 내거나 응했음")
        mdis$V15<- recode_factor(mdis$V15, '3'="취직시험응시(학교 추천)")
        mdis$V15<- recode_factor(mdis$V15, '4'="친구 친지 알선")
        mdis$V15<- recode_factor(mdis$V15, '5'="회사 사업장을 직접 방문")
        mdis$V15<- recode_factor(mdis$V15, '6'="회사엥 의한 스카우트")
        mdis$V15<- recode_factor(mdis$V15, '7'="자영업 구상")
        mdis$V15<- recode_factor(mdis$V15, '8'="기타 경로()")
        mdis$V16<- recode_factor(mdis$V16, '11'="있었음-보수가 적어서")
        mdis$V16<- recode_factor(mdis$V16, '12'="있었음-직장 또는 일거리의 전망이 없어서")
        mdis$V16<- recode_factor(mdis$V16, '13'="있었음-자영업을 하려고")
        mdis$V16<- recode_factor(mdis$V16, '14'="있었음-사업체의 폐업해고")
        mdis$V16<- recode_factor(mdis$V16, '15'="있었음--이사, 가사, 결혼")
        mdis$V16<- recode_factor(mdis$V16, '16'="있었음-군입대, 건강 등")
        mdis$V16<- recode_factor(mdis$V16, '17'="있었음-은퇴(정년퇴직)")
        mdis$V16<- recode_factor(mdis$V16, '18'="있었음-기타()")
        mdis$V16<- recode_factor(mdis$V16, '21'="없었음-가사")
        mdis$V16<- recode_factor(mdis$V16, '22'="없었음-통학")
        mdis$V16<- recode_factor(mdis$V16, '23'="없었음-군복무")
        mdis$V16<- recode_factor(mdis$V16, '24'="없었음-기타()")
        mdis$V18<- recode_factor(mdis$V18, '10'="있었음")
        mdis$V18<- recode_factor(mdis$V18, '21'="없었음-일시적병")
        mdis$V18<- recode_factor(mdis$V18, '22'="없었음-가사통학에 전념하므로")
        mdis$V18<- recode_factor(mdis$V18, '23'="없었음-기타(??)")
        mdis$V19<- recode_factor(mdis$V19, '11'="있었음-3개월미만")
        mdis$V19<- recode_factor(mdis$V19, '12'="있었음-3~6개월미만")
        mdis$V19<- recode_factor(mdis$V19, '13'="있었음-6~12개월미만")
        mdis$V19<- recode_factor(mdis$V19, '14'="있었음-1~3년미만")
        mdis$V19<- recode_factor(mdis$V19, '15'="있었음-3년이상")
        mdis$V19<- recode_factor(mdis$V19, '20'="없었음&lt;18번으로 감&gt;")
        mdis$V20<- recode_factor(mdis$V20, '1'="가정사정, 결혼")
        mdis$V20<- recode_factor(mdis$V20, '2'="취학")
        mdis$V20<- recode_factor(mdis$V20, '3'="건강, 연로, 은퇴")
        mdis$V20<- recode_factor(mdis$V20, '4'="계절적 사업완료")
        mdis$V20<- recode_factor(mdis$V20, '5'="직장불만")
        mdis$V20<- recode_factor(mdis$V20, '6'="사업이 잘 안되어서")
        mdis$V20<- recode_factor(mdis$V20, '7'="폐업, 해고")
        mdis$V20<- recode_factor(mdis$V20, '8'="기타()")
        mdis$V21<- recode_factor(mdis$V21, '1'="갖겠음")
        mdis$V21<- recode_factor(mdis$V21, '2'="갖지않겠음(*질문끝)")
        mdis$V23<- recode_factor(mdis$V23, '10'="그렇음")
        mdis$V23<- recode_factor(mdis$V23, '20'="그렇지 않음")
        mdis$V24<- recode_factor(mdis$V24, '11'="몸이 약해서 더 이상 일할 수 없어서")
        mdis$V24<- recode_factor(mdis$V24, '12'="가사, 통학으로")
        mdis$V24<- recode_factor(mdis$V24, '13'="장시간 일할 필요가 없어서")
        mdis$V24<- recode_factor(mdis$V24, '14'="일거리가 없어서")
        mdis$V24<- recode_factor(mdis$V24, '15'="기타(????)")
        mdis$V24<- recode_factor(mdis$V24, '20'="null")
        mdis$V24<- recode_factor(mdis$V24, '21'="일기불순, 일시적 병")
        mdis$V24<- recode_factor(mdis$V24, '22'="연가, 휴가")
        mdis$V24<- recode_factor(mdis$V24, '23'="조업중단")
        mdis$V24<- recode_factor(mdis$V24, '24'="일거리가 줄었음")
        mdis$V24<- recode_factor(mdis$V24, '25'="기타(????)")
        mdis$V27<- recode_factor(mdis$V27, '11'="고용주")
        mdis$V27<- recode_factor(mdis$V27, '12'="단독(자영자)")
        mdis$V27<- recode_factor(mdis$V27, '13'="무급가족종사자")
        mdis$V27<- recode_factor(mdis$V27, '22'="상용/임시")
        mdis$V27<- recode_factor(mdis$V27, '23'="일용")
        mdis$V29<- recode_factor(mdis$V29, '11'="주로 일한자")
        mdis$V29<- recode_factor(mdis$V29, '12'="틈틈이 일한자")
        mdis$V29<- recode_factor(mdis$V29, '13'="일시휴직자")
        mdis$V29<- recode_factor(mdis$V29, '21'="구직실업자")
        mdis$V29<- recode_factor(mdis$V29, '22'="비구직실업자")
        mdis$V29<- recode_factor(mdis$V29, '23'="신규실업자")
        mdis$V29<- recode_factor(mdis$V29, '24'="전직실업자")
        mdis$V29<- recode_factor(mdis$V29, '31'="비경제활동인구")
        mdis$V29<- recode_factor(mdis$V29, '32'="비경제활동인구")
        mdis$V30<- recode_factor(mdis$V30, '1'="농가")
        mdis$V30<- recode_factor(mdis$V30, '2'="비농가")

colnames(mdis) = c("가구일련번호"
, "가구원일련번호", "가구주관계", "성별", "연령", "출생년도", "배우관계", "교육정도", "수학여부", "활동상태", "취업여부", "일시휴직여부 및 이유", "구직여부", "비구직 실업여부", "구직경로", "전직유무 및 실업동기", "구직기간", "취업가능성 여부", "최종취업시기", "최근 불취업 이유", "취업의사"
, "취업시간", "평상시 취업시간", "평상시 36시간미만 일하는 이유", "산업", "직업", "종사상의 지위", "승수", "경제활동상태구분", "농가^비농가", "조사대상년월")

