#**********************************************************************  
#	*주의 사항
#		현재 스크립트 파일은 파일명만 출력되어 있습니다.
#		따라서, 저장된 추출 결과 파일의 경로를 'read.table' 또는 'read.fwf'에 추가하여야 합니다.
#	예) 다운로드 받은 폴더명 : C:\Download
#	  ※ 파일 경로 추가 : "[다운로드 받은 폴더명]\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt"
# 		read.table("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#		또는
#		read.fwf("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#
#		R 스크립트는 R 에서 파일 경로만 수정하시면 바로 실행(Ctrl+Alt+R)가능하며,
#		데이터셋 생성 후에 R 의 여러 가지 분석 기능을 사용할 수 있습니다.
#
#**********************************************************************

install.packages("dplyr")
library(dplyr)

mdis <- read.table("1985_경제활동인구조사 연간자료1 (1981-1999)_20250711_01423.csv", header=FALSE, sep=",", colClasses = c("character"
, "character", "character", "character", "numeric", "numeric", "character", "character", "character", "character", "character", "character", "character", "character", "character", "numeric", "character", "character", "character", "numeric", "character"
, "numeric", "numeric", "character", "character", "character", "character", "character", "character"), skip=1, na.string=c("*","**","***","****","*****","******","*******","********","*********","**********","."))

        mdis$V3<- recode_factor(mdis$V3, '0'="동거인")
        mdis$V3<- recode_factor(mdis$V3, '1'="가구주")
        mdis$V3<- recode_factor(mdis$V3, '2'="배우자")
        mdis$V3<- recode_factor(mdis$V3, '3'="미혼자녀")
        mdis$V3<- recode_factor(mdis$V3, '4'="미혼형제자매")
        mdis$V3<- recode_factor(mdis$V3, '5'="부모(장인, 장모포함)")
        mdis$V3<- recode_factor(mdis$V3, '6'="조부모")
        mdis$V3<- recode_factor(mdis$V3, '7'="기혼자녀, 그가족")
        mdis$V3<- recode_factor(mdis$V3, '8'="기혼형제 자매, 그가족")
        mdis$V3<- recode_factor(mdis$V3, '9'="기타친척")
        mdis$V4<- recode_factor(mdis$V4, '1'="남자")
        mdis$V4<- recode_factor(mdis$V4, '2'="여자")
        mdis$V7<- recode_factor(mdis$V7, '1'="미혼")
        mdis$V7<- recode_factor(mdis$V7, '2'="유배우")
        mdis$V7<- recode_factor(mdis$V7, '3'="사별")
        mdis$V7<- recode_factor(mdis$V7, '4'="이혼")
        mdis$V8<- recode_factor(mdis$V8, '1'="국민학교 이하")
        mdis$V8<- recode_factor(mdis$V8, '2'="중학교")
        mdis$V8<- recode_factor(mdis$V8, '3'="고등학교")
        mdis$V8<- recode_factor(mdis$V8, '4'="초대 및 전문대")
        mdis$V8<- recode_factor(mdis$V8, '5'="대학이상")
        mdis$V9<- recode_factor(mdis$V9, '1'="졸업")
        mdis$V9<- recode_factor(mdis$V9, '2'="재학")
        mdis$V9<- recode_factor(mdis$V9, '3'="중퇴")
        mdis$V9<- recode_factor(mdis$V9, '4'="안다녔음")
        mdis$V10<- recode_factor(mdis$V10, '1'="일하였음&lt;(가-1)로감&gt;")
        mdis$V10<- recode_factor(mdis$V10, '2'="일시휴직")
        mdis$V10<- recode_factor(mdis$V10, '3'="구직활동")
        mdis$V10<- recode_factor(mdis$V10, '4'="가사")
        mdis$V10<- recode_factor(mdis$V10, '5'="통학")
        mdis$V10<- recode_factor(mdis$V10, '6'="연소연로")
        mdis$V10<- recode_factor(mdis$V10, '7'="불구")
        mdis$V10<- recode_factor(mdis$V10, '8'="기타(이유:????)")
        mdis$V11<- recode_factor(mdis$V11, '1'="있었음&lt;(가-1)로 감&gt;")
        mdis$V11<- recode_factor(mdis$V11, '2'="없었음")
        mdis$V12<- recode_factor(mdis$V12, '11'="일시적 병&lt;(가-1)로 감&gt;")
        mdis$V12<- recode_factor(mdis$V12, '12'="연가 또는 휴가&lt;(가-1)로 감&gt;")
        mdis$V12<- recode_factor(mdis$V12, '13'="노동쟁의&lt;(가-1)로 감&gt;")
        mdis$V12<- recode_factor(mdis$V12, '14'="조업중단&lt;(가-1)로 감&gt;")
        mdis$V12<- recode_factor(mdis$V12, '15'="기타(????)")
        mdis$V12<- recode_factor(mdis$V12, '20'="없었음")
        mdis$V13<- recode_factor(mdis$V13, '1'="구해보았음(11번이동)")
        mdis$V13<- recode_factor(mdis$V13, '2'="불가피한 사유로 구해보지 못했음(11번이동)")
        mdis$V13<- recode_factor(mdis$V13, '3'="구해보지 않았음(12번 이동)")
        mdis$V14<- recode_factor(mdis$V14, '1'="있었음&lt;(나-1)로 감)")
        mdis$V14<- recode_factor(mdis$V14, '2'="없었음")
        mdis$V15<- recode_factor(mdis$V15, '1'="하겠음&lt;(다-1)로감&gt;")
        mdis$V15<- recode_factor(mdis$V15, '2'="하지 않겠음(* 질문끝)")
        mdis$V17<- recode_factor(mdis$V17, '1'="18시간 미만 무급가족종사자&lt;10으로 감)&gt;")
        mdis$V17<- recode_factor(mdis$V17, '2'="1~35시간&lt;(가-2)로 감&gt;")
        mdis$V17<- recode_factor(mdis$V17, '3'="36시간이상&lt;(라-1)로 감&gt;")
        mdis$V17<- recode_factor(mdis$V17, '11'="건강때문에")
        mdis$V17<- recode_factor(mdis$V17, '12'="가사, 통학으로")
        mdis$V17<- recode_factor(mdis$V17, '13'="더 이상 일할 필요가 없어서")
        mdis$V17<- recode_factor(mdis$V17, '14'="일거리가 없어서")
        mdis$V17<- recode_factor(mdis$V17, '15'="기타(????)")
        mdis$V17<- recode_factor(mdis$V17, '21'="일시적 병")
        mdis$V17<- recode_factor(mdis$V17, '22'="연가, 휴가")
        mdis$V17<- recode_factor(mdis$V17, '23'="조업중단(일기불순, 기계고장 등)")
        mdis$V17<- recode_factor(mdis$V17, '24'="조업단축")
        mdis$V17<- recode_factor(mdis$V17, '25'="기타(????)")
        mdis$V18<- recode_factor(mdis$V18, '10'="그렇음")
        mdis$V18<- recode_factor(mdis$V18, '20'="그렇지 않음")
        mdis$V19<- recode_factor(mdis$V19, '11'="몸이 약해서 더 이상 일할 수 없어서")
        mdis$V19<- recode_factor(mdis$V19, '12'="가사, 통학으로")
        mdis$V19<- recode_factor(mdis$V19, '13'="장시간 일할 필요가 없어서")
        mdis$V19<- recode_factor(mdis$V19, '14'="일거리가 없어서")
        mdis$V19<- recode_factor(mdis$V19, '15'="기타(????)")
        mdis$V19<- recode_factor(mdis$V19, '21'="일기불순, 일시적 병")
        mdis$V19<- recode_factor(mdis$V19, '22'="연가, 휴가")
        mdis$V19<- recode_factor(mdis$V19, '23'="조업중단")
        mdis$V19<- recode_factor(mdis$V19, '24'="일거리가 줄었음")
        mdis$V19<- recode_factor(mdis$V19, '25'="기타(????)")
        mdis$V21<- recode_factor(mdis$V21, '1'="신규실업(* 질문끝)")
        mdis$V21<- recode_factor(mdis$V21, '2'="보수및작업환경 불만족&lt;(라-1)로감&gt;")
        mdis$V21<- recode_factor(mdis$V21, '3'="장래성이 없어서&lt;(라-1)로감&gt;")
        mdis$V21<- recode_factor(mdis$V21, '4'="폐업, 해고&lt;(라-1)로감&gt;")
        mdis$V21<- recode_factor(mdis$V21, '5'="정년퇴직&lt;(라-1)로감&gt;")
        mdis$V21<- recode_factor(mdis$V21, '6'="자기사업을 하려고&lt;(라-1)로감&gt;")
        mdis$V21<- recode_factor(mdis$V21, '7'="사업부진&lt;(라-1)로감&gt;")
        mdis$V21<- recode_factor(mdis$V21, '8'="기타(????)&lt;(라-1)로감&gt;")
        mdis$V24<- recode_factor(mdis$V24, '11'="고용주")
        mdis$V24<- recode_factor(mdis$V24, '12'="자영자")
        mdis$V24<- recode_factor(mdis$V24, '13'="가족봉사자")
        mdis$V24<- recode_factor(mdis$V24, '21'="상용")
        mdis$V24<- recode_factor(mdis$V24, '22'="임시")
        mdis$V24<- recode_factor(mdis$V24, '23'="일용")
        mdis$V27<- recode_factor(mdis$V27, '11'="취업자")
        mdis$V27<- recode_factor(mdis$V27, '12'="일시휴직자")
        mdis$V27<- recode_factor(mdis$V27, '21'="신규실업자")
        mdis$V27<- recode_factor(mdis$V27, '22'="전직실업자")
        mdis$V27<- recode_factor(mdis$V27, '31'="구직경험자")
        mdis$V27<- recode_factor(mdis$V27, '32'="6개월내 구직자")
        mdis$V27<- recode_factor(mdis$V27, '33'="6개월내 비구직자")
        mdis$V27<- recode_factor(mdis$V27, '34'="순수비경제활동인구")
        mdis$V28<- recode_factor(mdis$V28, '1'="농가")
        mdis$V28<- recode_factor(mdis$V28, '2'="비농가")
        mdis$V29<- recode_factor(mdis$V29, '1'="시부")
        mdis$V29<- recode_factor(mdis$V29, '2'="군부")

colnames(mdis) = c("가구 일련번호"
, "가구원 일련번호", "가구주관계", "성별", "연령", "출생년도", "배우관계", "교육정도", "수학여부", "활동상태", "취업여부", "일시휴직여부 및 이유", "1주간의 구직여부", "취업가능성 여부", "취업의사유무", "취업시간", "조사요원 점검란(취업구분)", "평상시 취업시간", "평상시 36시간미만 일하는 이유", "구직기간", "전직유무 및 실업동기"
, "산업", "직업", "종사상의 지위", "조사대상년월", "승수", "경제활동상태구분", "농가^비농가", "시부.군부")

