#**********************************************************************  
#	*주의 사항
#		현재 스크립트 파일은 파일명만 출력되어 있습니다.
#		따라서, 저장된 추출 결과 파일의 경로를 'read.table' 또는 'read.fwf'에 추가하여야 합니다.
#	예) 다운로드 받은 폴더명 : C:\Download
#	  ※ 파일 경로 추가 : "[다운로드 받은 폴더명]\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt"
# 		read.table("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#		또는
#		read.fwf("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#
#		R 스크립트는 R 에서 파일 경로만 수정하시면 바로 실행(Ctrl+Alt+R)가능하며,
#		데이터셋 생성 후에 R 의 여러 가지 분석 기능을 사용할 수 있습니다.
#
#**********************************************************************

install.packages("dplyr")
library(dplyr)

mdis <- read.table("1987_경제활동인구조사 연간자료1 (1981-1999)_20250711_71199.csv", header=FALSE, sep=",", colClasses = c("character"
, "character", "character", "character", "numeric", "numeric", "character", "character", "character", "character", "character", "character", "character", "character", "character", "numeric", "character", "character", "numeric", "character", "character"
, "character", "character", "numeric", "numeric", "character"), skip=1, na.string=c("*","**","***","****","*****","******","*******","********","*********","**********","."))

        mdis$V3<- recode_factor(mdis$V3, '0'="조사대상아님")
        mdis$V3<- recode_factor(mdis$V3, '1'="가구주")
        mdis$V3<- recode_factor(mdis$V3, '2'="배우자")
        mdis$V3<- recode_factor(mdis$V3, '3'="미혼자녀")
        mdis$V3<- recode_factor(mdis$V3, '4'="기혼자녀")
        mdis$V3<- recode_factor(mdis$V3, '5'="손자녀")
        mdis$V3<- recode_factor(mdis$V3, '6'="부모")
        mdis$V3<- recode_factor(mdis$V3, '7'="조부모")
        mdis$V3<- recode_factor(mdis$V3, '8'="미혼형제자매")
        mdis$V3<- recode_factor(mdis$V3, '9'="기타")
        mdis$V4<- recode_factor(mdis$V4, '1'="남자")
        mdis$V4<- recode_factor(mdis$V4, '2'="여자")
        mdis$V7<- recode_factor(mdis$V7, '1'="미혼")
        mdis$V7<- recode_factor(mdis$V7, '2'="유배우")
        mdis$V7<- recode_factor(mdis$V7, '3'="사별 ")
        mdis$V7<- recode_factor(mdis$V7, '4'="이혼")
        mdis$V8<- recode_factor(mdis$V8, '1'="초등학교 이하")
        mdis$V8<- recode_factor(mdis$V8, '2'="중학교")
        mdis$V8<- recode_factor(mdis$V8, '3'="고등학교")
        mdis$V8<- recode_factor(mdis$V8, '4'="초대 및 전문대")
        mdis$V8<- recode_factor(mdis$V8, '5'="대학이상")
        mdis$V9<- recode_factor(mdis$V9, '1'="졸업")
        mdis$V9<- recode_factor(mdis$V9, '2'="재학")
        mdis$V9<- recode_factor(mdis$V9, '3'="중퇴")
        mdis$V9<- recode_factor(mdis$V9, '4'="안다녔음")
        mdis$V10<- recode_factor(mdis$V10, '1'="일하였음")
        mdis$V10<- recode_factor(mdis$V10, '2'="일시휴직")
        mdis$V10<- recode_factor(mdis$V10, '3'="구직활동")
        mdis$V10<- recode_factor(mdis$V10, '4'="가사")
        mdis$V10<- recode_factor(mdis$V10, '5'="통학")
        mdis$V10<- recode_factor(mdis$V10, '6'="연소,연로")
        mdis$V10<- recode_factor(mdis$V10, '7'="불구")
        mdis$V10<- recode_factor(mdis$V10, '8'="기타")
        mdis$V11<- recode_factor(mdis$V11, '0'="조사대상아님")
        mdis$V11<- recode_factor(mdis$V11, '1'="있었음")
        mdis$V11<- recode_factor(mdis$V11, '2'="없었음")
        mdis$V12<- recode_factor(mdis$V12, '00'="조사대상아님")
        mdis$V12<- recode_factor(mdis$V12, '11'="일시적 병, 사고")
        mdis$V12<- recode_factor(mdis$V12, '12'="연가 또는 휴가")
        mdis$V12<- recode_factor(mdis$V12, '13'="노동쟁의")
        mdis$V12<- recode_factor(mdis$V12, '14'="조업중단")
        mdis$V12<- recode_factor(mdis$V12, '15'="기타")
        mdis$V12<- recode_factor(mdis$V12, '20'="없었음")
        mdis$V13<- recode_factor(mdis$V13, '0'="조사대상아님")
        mdis$V13<- recode_factor(mdis$V13, '1'="구해보았음")
        mdis$V13<- recode_factor(mdis$V13, '2'="불가피한 사유로 구해보지않았음")
        mdis$V13<- recode_factor(mdis$V13, '3'="구해보지 않았음")
        mdis$V14<- recode_factor(mdis$V14, '0'="조사대상아님")
        mdis$V14<- recode_factor(mdis$V14, '1'="있었음")
        mdis$V14<- recode_factor(mdis$V14, '2'="없었음")
        mdis$V15<- recode_factor(mdis$V15, '0'="조사대상아님")
        mdis$V15<- recode_factor(mdis$V15, '1'="하겠음")
        mdis$V15<- recode_factor(mdis$V15, '2'="하지않겠음")
        mdis$V17<- recode_factor(mdis$V17, '0'="조사대상아님")
        mdis$V17<- recode_factor(mdis$V17, '1'="18시간미만 무급가족종사자")
        mdis$V17<- recode_factor(mdis$V17, '2'="1~35시간")
        mdis$V17<- recode_factor(mdis$V17, '3'="36시간이상")
        mdis$V18<- recode_factor(mdis$V18, '00'="조사대상아님")
        mdis$V18<- recode_factor(mdis$V18, '11'="건강때문에")
        mdis$V18<- recode_factor(mdis$V18, '12'="가사, 통학으로")
        mdis$V18<- recode_factor(mdis$V18, '13'="더 이상 일할 필요가 없어서")
        mdis$V18<- recode_factor(mdis$V18, '14'="일거리가 없어서")
        mdis$V18<- recode_factor(mdis$V18, '15'="기타")
        mdis$V18<- recode_factor(mdis$V18, '21'="일시적병 ")
        mdis$V18<- recode_factor(mdis$V18, '22'="연가,휴가")
        mdis$V18<- recode_factor(mdis$V18, '23'="조업중단")
        mdis$V18<- recode_factor(mdis$V18, '24'="조업단축")
        mdis$V18<- recode_factor(mdis$V18, '25'="기타")
        mdis$V20<- recode_factor(mdis$V20, '0'="조사대상아님")
        mdis$V20<- recode_factor(mdis$V20, '1'="신규실업")
        mdis$V20<- recode_factor(mdis$V20, '2'="보수 및 작업환경불만족")
        mdis$V20<- recode_factor(mdis$V20, '3'="장래성이 없어서")
        mdis$V20<- recode_factor(mdis$V20, '4'="폐업,해고")
        mdis$V20<- recode_factor(mdis$V20, '5'="정년퇴직 ")
        mdis$V20<- recode_factor(mdis$V20, '6'="자기 사업을 하려고")
        mdis$V20<- recode_factor(mdis$V20, '7'="사업부진")
        mdis$V20<- recode_factor(mdis$V20, '8'="기타")
        mdis$V21<- recode_factor(mdis$V21, '0'="조사대상아님")
        mdis$V21<- recode_factor(mdis$V21, '1'="농업, 수렵, 임업 및 어업(11-13)")
        mdis$V21<- recode_factor(mdis$V21, '2'="광 업(21-29)")
        mdis$V21<- recode_factor(mdis$V21, '3'="제 조 업(31-39)")
        mdis$V21<- recode_factor(mdis$V21, '4'="전기, 가스 및 수도사업(41-42)")
        mdis$V21<- recode_factor(mdis$V21, '5'="건설업(51-52)")
        mdis$V21<- recode_factor(mdis$V21, '6'="도소매 및 음식숙박업(61-63)")
        mdis$V21<- recode_factor(mdis$V21, '7'="운수, 창고 및 통신업(71-72)")
        mdis$V21<- recode_factor(mdis$V21, '8'="금융, 보험, 부동산 및 사업서비스업(81-84)")
        mdis$V21<- recode_factor(mdis$V21, '9'="사회 및 개인서비스업(91-96)")
        mdis$V22<- recode_factor(mdis$V22, '0'="조사대상아님")
        mdis$V22<- recode_factor(mdis$V22, '1'="전문,기술 및 관련직 종사자")
        mdis$V22<- recode_factor(mdis$V22, '2'="행정 및 관리직 종사자")
        mdis$V22<- recode_factor(mdis$V22, '3'="사무 및 관리직 종사자")
        mdis$V22<- recode_factor(mdis$V22, '4'="판매종사자")
        mdis$V22<- recode_factor(mdis$V22, '5'="서비스직 종사자")
        mdis$V22<- recode_factor(mdis$V22, '6'="농업,축산업,임업, 수산업 및 수렵업  종사자")
        mdis$V22<- recode_factor(mdis$V22, '7'="생산 및 관련종사자,운수장비운전사 및 단순노무자")
        mdis$V22<- recode_factor(mdis$V22, '8'="생산 및 관련종사자,운수장비운전사 및 단순노무자")
        mdis$V22<- recode_factor(mdis$V22, '9'="생산 및 관련종사자,운수장비운전사 및 단순노무자")
        mdis$V23<- recode_factor(mdis$V23, '00'="조사대상아님")
        mdis$V23<- recode_factor(mdis$V23, '11'="고용주")
        mdis$V23<- recode_factor(mdis$V23, '12'="자영자 ")
        mdis$V23<- recode_factor(mdis$V23, '13'="가족종사자")
        mdis$V23<- recode_factor(mdis$V23, '22'="상용+임시(상시근로자)")
        mdis$V23<- recode_factor(mdis$V23, '23'="일용근로자")
        mdis$V26<- recode_factor(mdis$V26, '11'="취업자")
        mdis$V26<- recode_factor(mdis$V26, '12'="일시휴직자")
        mdis$V26<- recode_factor(mdis$V26, '21'="신규실업자")
        mdis$V26<- recode_factor(mdis$V26, '22'="전직실업자")
        mdis$V26<- recode_factor(mdis$V26, '31'="구직경험자")
        mdis$V26<- recode_factor(mdis$V26, '32'="6개월내 구직자")
        mdis$V26<- recode_factor(mdis$V26, '33'="6개월내 비구직자")
        mdis$V26<- recode_factor(mdis$V26, '34'="순수비경제활동인구")

colnames(mdis) = c("가구번호"
, "가구원번호", "가구주관계", "성별", "연령", "생년월(yymm)", "혼인상태", "교육정도", "교육정도(수학여부)", "활동상태", "취업여부", "일시휴직여부 및 이유", "1주간 구직활동 여부", "취업가능성여부", "취업의사유무", "취업시간", "취업구분", "1주에 36시간 미만 일할경우", "구직기간", "전직유무 및 실업동기", "산업"
, "직업", "종사상지위_자영근로자^임금근로자", "조사기준일", "승수", "경제활동분류")

