#**********************************************************************  
#	*주의 사항
#		현재 스크립트 파일은 파일명만 출력되어 있습니다.
#		따라서, 저장된 추출 결과 파일의 경로를 'read.table' 또는 'read.fwf'에 추가하여야 합니다.
#	예) 다운로드 받은 폴더명 : C:\Download
#	  ※ 파일 경로 추가 : "[다운로드 받은 폴더명]\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt"
# 		read.table("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#		또는
#		read.fwf("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#
#		R 스크립트는 R 에서 파일 경로만 수정하시면 바로 실행(Ctrl+Alt+R)가능하며,
#		데이터셋 생성 후에 R 의 여러 가지 분석 기능을 사용할 수 있습니다.
#
#**********************************************************************

install.packages("dplyr")
library(dplyr)

mdis <- read.table("1992_경제활동인구조사 연간자료1 (1981-1999)_20250711_21603.csv", header=FALSE, sep=",", colClasses = c("character"
, "character", "character", "character", "numeric", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "numeric", "character", "character", "numeric", "character"
, "character", "character", "character", "character", "character", "character", "character", "numeric"), skip=1, na.string=c("*","**","***","****","*****","******","*******","********","*********","**********","."))

        mdis$V3<- recode_factor(mdis$V3, '0'="동거인")
        mdis$V3<- recode_factor(mdis$V3, '1'="가구주")
        mdis$V3<- recode_factor(mdis$V3, '2'="가구주의 배우자")
        mdis$V3<- recode_factor(mdis$V3, '3'="미혼자녀")
        mdis$V3<- recode_factor(mdis$V3, '4'="미혼형제, 자매")
        mdis$V3<- recode_factor(mdis$V3, '5'="부모(장인, 장모포함)")
        mdis$V3<- recode_factor(mdis$V3, '6'="조부모")
        mdis$V3<- recode_factor(mdis$V3, '7'="기혼자녀 및 그 가족")
        mdis$V3<- recode_factor(mdis$V3, '8'="기혼형제, 자매 및 그 가족")
        mdis$V3<- recode_factor(mdis$V3, '9'="기타 친척")
        mdis$V4<- recode_factor(mdis$V4, '1'="남자")
        mdis$V4<- recode_factor(mdis$V4, '2'="여자")
        mdis$V6<- recode_factor(mdis$V6, '01'="15~19세")
        mdis$V6<- recode_factor(mdis$V6, '02'="20~24세")
        mdis$V6<- recode_factor(mdis$V6, '03'="25~29세")
        mdis$V6<- recode_factor(mdis$V6, '04'="30~34세")
        mdis$V6<- recode_factor(mdis$V6, '05'="35~39세")
        mdis$V6<- recode_factor(mdis$V6, '06'="40~44세")
        mdis$V6<- recode_factor(mdis$V6, '07'="45~49세")
        mdis$V6<- recode_factor(mdis$V6, '08'="50~54세")
        mdis$V6<- recode_factor(mdis$V6, '09'="55~59세")
        mdis$V6<- recode_factor(mdis$V6, '10'="60~64세")
        mdis$V6<- recode_factor(mdis$V6, '11'="65세이상")
        mdis$V8<- recode_factor(mdis$V8, '1'="미혼")
        mdis$V8<- recode_factor(mdis$V8, '2'="유배우")
        mdis$V8<- recode_factor(mdis$V8, '3'="사별")
        mdis$V8<- recode_factor(mdis$V8, '4'="이혼")
        mdis$V9<- recode_factor(mdis$V9, '0'="무학")
        mdis$V9<- recode_factor(mdis$V9, '1'="초등학교")
        mdis$V9<- recode_factor(mdis$V9, '2'="중학교")
        mdis$V9<- recode_factor(mdis$V9, '3'="고등학교")
        mdis$V9<- recode_factor(mdis$V9, '4'="초대 및 전문대")
        mdis$V9<- recode_factor(mdis$V9, '5'="대학이상")
        mdis$V10<- recode_factor(mdis$V10, '1'="졸업")
        mdis$V10<- recode_factor(mdis$V10, '2'="재학")
        mdis$V10<- recode_factor(mdis$V10, '3'="중퇴")
        mdis$V11<- recode_factor(mdis$V11, '1'="일하였음")
        mdis$V11<- recode_factor(mdis$V11, '2'="일시휴직")
        mdis$V11<- recode_factor(mdis$V11, '3'="구직활동")
        mdis$V11<- recode_factor(mdis$V11, '4'="가사")
        mdis$V11<- recode_factor(mdis$V11, '5'="통학")
        mdis$V11<- recode_factor(mdis$V11, '6'="연소,연로")
        mdis$V11<- recode_factor(mdis$V11, '7'="불구")
        mdis$V11<- recode_factor(mdis$V11, '8'="기타")
        mdis$V12<- recode_factor(mdis$V12, '1'="있었음")
        mdis$V12<- recode_factor(mdis$V12, '2'="없었음")
        mdis$V13<- recode_factor(mdis$V13, '11'="일시적 병. 사고")
        mdis$V13<- recode_factor(mdis$V13, '12'="연가,휴가")
        mdis$V13<- recode_factor(mdis$V13, '13'="노동쟁의")
        mdis$V13<- recode_factor(mdis$V13, '14'="조업중단")
        mdis$V13<- recode_factor(mdis$V13, '15'="기타")
        mdis$V13<- recode_factor(mdis$V13, '20'="없었음")
        mdis$V14<- recode_factor(mdis$V14, '1'="구해보았음")
        mdis$V14<- recode_factor(mdis$V14, '2'="불가피한사유로 구해보지않았음")
        mdis$V14<- recode_factor(mdis$V14, '3'="구해보지 않았음")
        mdis$V15<- recode_factor(mdis$V15, '1'="있었음")
        mdis$V15<- recode_factor(mdis$V15, '2'="없었음")
        mdis$V16<- recode_factor(mdis$V16, '1'="하겠음")
        mdis$V16<- recode_factor(mdis$V16, '2'="하지않겠음")
        mdis$V18<- recode_factor(mdis$V18, '1'="18시간미만 무급가족종사자")
        mdis$V18<- recode_factor(mdis$V18, '2'="1~35시간")
        mdis$V18<- recode_factor(mdis$V18, '3'="36시간이상")
        mdis$V19<- recode_factor(mdis$V19, '11'="건강때문에")
        mdis$V19<- recode_factor(mdis$V19, '12'="가사.통학으로")
        mdis$V19<- recode_factor(mdis$V19, '13'="더 이상 일할 필요가 없어서")
        mdis$V19<- recode_factor(mdis$V19, '14'="일거리가 없어서")
        mdis$V19<- recode_factor(mdis$V19, '15'="기타")
        mdis$V19<- recode_factor(mdis$V19, '21'="일시적병사고")
        mdis$V19<- recode_factor(mdis$V19, '22'="연가.휴가")
        mdis$V19<- recode_factor(mdis$V19, '23'="조업중단")
        mdis$V19<- recode_factor(mdis$V19, '24'="조업단축")
        mdis$V19<- recode_factor(mdis$V19, '25'="기타")
        mdis$V21<- recode_factor(mdis$V21, '1'="신규실업")
        mdis$V21<- recode_factor(mdis$V21, '2'="보수및 작업환경불만족")
        mdis$V21<- recode_factor(mdis$V21, '3'="장래성이없어서")
        mdis$V21<- recode_factor(mdis$V21, '4'="폐업.해고")
        mdis$V21<- recode_factor(mdis$V21, '5'="정년퇴직")
        mdis$V21<- recode_factor(mdis$V21, '6'="자기사업하려고")
        mdis$V21<- recode_factor(mdis$V21, '7'="사업부진")
        mdis$V21<- recode_factor(mdis$V21, '8'="기타")
        mdis$V22<- recode_factor(mdis$V22, '1'="농업, 수렵, 임업 및 어업(11-13)")
        mdis$V22<- recode_factor(mdis$V22, '2'="광 업(21-29)")
        mdis$V22<- recode_factor(mdis$V22, '3'="제 조 업(31-39)")
        mdis$V22<- recode_factor(mdis$V22, '4'="전기, 가스 및 수도사업(41-42)")
        mdis$V22<- recode_factor(mdis$V22, '5'="건설업(51-52)")
        mdis$V22<- recode_factor(mdis$V22, '6'="도소매 및 음식숙박업(61-63)")
        mdis$V22<- recode_factor(mdis$V22, '7'="운수, 창고 및 통신업(71-72)")
        mdis$V22<- recode_factor(mdis$V22, '8'="금융, 보험, 부동산 및 사업서비스업(81-84)")
        mdis$V22<- recode_factor(mdis$V22, '9'="사회 및 개인서비스업(91-96)")
        mdis$V23<- recode_factor(mdis$V23, '0'="전문,기술 및 관련직 종사자")
        mdis$V23<- recode_factor(mdis$V23, '1'="전문,기술 및 관련직 종사자")
        mdis$V23<- recode_factor(mdis$V23, '2'="행정 및 관리직 종사자")
        mdis$V23<- recode_factor(mdis$V23, '3'="사무 및 관리직 종사자")
        mdis$V23<- recode_factor(mdis$V23, '4'="판매종사자")
        mdis$V23<- recode_factor(mdis$V23, '5'="서비스직 종사자")
        mdis$V23<- recode_factor(mdis$V23, '6'="농업,축산업,임업, 수산업 및 수렵업  종사자")
        mdis$V23<- recode_factor(mdis$V23, '7'="생산 및 관련종사자,운수장비운전사 및 단순노무자")
        mdis$V23<- recode_factor(mdis$V23, '8'="생산 및 관련종사자,운수장비운전사 및 단순노무자")
        mdis$V23<- recode_factor(mdis$V23, '9'="생산 및 관련종사자,운수장비운전사 및 단순노무자")
        mdis$V24<- recode_factor(mdis$V24, '11'="고용주")
        mdis$V24<- recode_factor(mdis$V24, '12'="자영자")
        mdis$V24<- recode_factor(mdis$V24, '13'="무급가족종사자")
        mdis$V24<- recode_factor(mdis$V24, '21'="상용근로자")
        mdis$V24<- recode_factor(mdis$V24, '22'="임시근로자")
        mdis$V24<- recode_factor(mdis$V24, '23'="일용근로자")
        mdis$V26<- recode_factor(mdis$V26, '11'="취업자")
        mdis$V26<- recode_factor(mdis$V26, '12'="일시휴직자")
        mdis$V26<- recode_factor(mdis$V26, '21'="신규실업자")
        mdis$V26<- recode_factor(mdis$V26, '22'="전직실업자")
        mdis$V26<- recode_factor(mdis$V26, '31'="구직경험자")
        mdis$V26<- recode_factor(mdis$V26, '32'="6개월내 구직자")
        mdis$V26<- recode_factor(mdis$V26, '33'="6개월내 비구직자")
        mdis$V26<- recode_factor(mdis$V26, '34'="순수비경제활동인구")
        mdis$V27<- recode_factor(mdis$V27, '1'="농가")
        mdis$V27<- recode_factor(mdis$V27, '2'="비농가")
        mdis$V28<- recode_factor(mdis$V28, '1'="시부")
        mdis$V28<- recode_factor(mdis$V28, '2'="군부")

colnames(mdis) = c("가구일련번호"
, "가구원일련번호", "가구주와의 관계", "성별", "만연령", "연령계층", "생년월", "혼인상태", "교육정도변환(학력)", "교육정도변환(수학여부)", "활동상태", "취업여부", "일시휴직이유", "1주간구직활동 여부", "취업가능성여부", "취업의사유무", "취업시간", "취업구분", "평상시 취업시간", "구직기간", "전직유무 및 실업동기"
, "산업", "직업", "종사상지위", "조사년월일", "경제활동분류", "가구구분", "시.군부(93년 자료 없음)", "승수")

