#**********************************************************************  
#	*주의 사항
#		현재 스크립트 파일은 파일명만 출력되어 있습니다.
#		따라서, 저장된 추출 결과 파일의 경로를 'read.table' 또는 'read.fwf'에 추가하여야 합니다.
#	예) 다운로드 받은 폴더명 : C:\Download
#	  ※ 파일 경로 추가 : "[다운로드 받은 폴더명]\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt"
# 		read.table("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#		또는
#		read.fwf("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#
#		R 스크립트는 R 에서 파일 경로만 수정하시면 바로 실행(Ctrl+Alt+R)가능하며,
#		데이터셋 생성 후에 R 의 여러 가지 분석 기능을 사용할 수 있습니다.
#
#**********************************************************************

install.packages("dplyr")
library(dplyr)

mdis <- read.table("1998_경제활동인구조사 연간자료1 (1981-1999)_20250711_66054.csv", header=FALSE, sep=",", colClasses = c("character"
, "character", "character", "character", "numeric", "character", "numeric", "numeric", "character", "character", "character", "character", "character", "character", "character", "numeric", "character", "character", "character", "character", "character"
, "character", "character", "character", "character", "character", "character", "character", "character", "character", "numeric", "numeric", "numeric", "character", "character", "character", "character", "character", "character", "numeric"), skip=1, na.string=c("*","**","***","****","*****","******","*******","********","*********","**********","."))

        mdis$V3<- recode_factor(mdis$V3, '1'="가구주")
        mdis$V3<- recode_factor(mdis$V3, '2'="배우자")
        mdis$V3<- recode_factor(mdis$V3, '3'="미혼자녀")
        mdis$V3<- recode_factor(mdis$V3, '4'="미혼형제.자매")
        mdis$V3<- recode_factor(mdis$V3, '5'="부모(장인,장모)")
        mdis$V3<- recode_factor(mdis$V3, '6'="조부모")
        mdis$V3<- recode_factor(mdis$V3, '7'="기타 친인척")
        mdis$V3<- recode_factor(mdis$V3, '8'="동거인")
        mdis$V4<- recode_factor(mdis$V4, '1'="남자")
        mdis$V4<- recode_factor(mdis$V4, '2'="여자")
        mdis$V6<- recode_factor(mdis$V6, '01'="15~19세")
        mdis$V6<- recode_factor(mdis$V6, '02'="20~24세")
        mdis$V6<- recode_factor(mdis$V6, '03'="25~29세")
        mdis$V6<- recode_factor(mdis$V6, '04'="30~34세")
        mdis$V6<- recode_factor(mdis$V6, '05'="35~39세")
        mdis$V6<- recode_factor(mdis$V6, '06'="40~44세")
        mdis$V6<- recode_factor(mdis$V6, '07'="45~49세")
        mdis$V6<- recode_factor(mdis$V6, '08'="50~54세")
        mdis$V6<- recode_factor(mdis$V6, '09'="55~59세")
        mdis$V6<- recode_factor(mdis$V6, '10'="60~64세")
        mdis$V6<- recode_factor(mdis$V6, '11'="65세이상")
        mdis$V9<- recode_factor(mdis$V9, '0'="무학")
        mdis$V9<- recode_factor(mdis$V9, '1'="초등학교")
        mdis$V9<- recode_factor(mdis$V9, '2'="중학교")
        mdis$V9<- recode_factor(mdis$V9, '3'="고등학교")
        mdis$V9<- recode_factor(mdis$V9, '4'="전문대(초급대)")
        mdis$V9<- recode_factor(mdis$V9, '5'="대학이상")
        mdis$V10<- recode_factor(mdis$V10, '0'="조사대상아님")
        mdis$V10<- recode_factor(mdis$V10, '1'="졸업")
        mdis$V10<- recode_factor(mdis$V10, '2'="재학")
        mdis$V10<- recode_factor(mdis$V10, '3'="중퇴")
        mdis$V10<- recode_factor(mdis$V10, '4'="휴학")
        mdis$V11<- recode_factor(mdis$V11, '1'="미혼")
        mdis$V11<- recode_factor(mdis$V11, '2'="유배우")
        mdis$V11<- recode_factor(mdis$V11, '3'="사별")
        mdis$V11<- recode_factor(mdis$V11, '4'="이혼")
        mdis$V12<- recode_factor(mdis$V12, '1'="일하였음")
        mdis$V12<- recode_factor(mdis$V12, '2'="일시휴직")
        mdis$V12<- recode_factor(mdis$V12, '3'="구직활동")
        mdis$V12<- recode_factor(mdis$V12, '4'="육아")
        mdis$V12<- recode_factor(mdis$V12, '5'="가사")
        mdis$V12<- recode_factor(mdis$V12, '6'="통학")
        mdis$V12<- recode_factor(mdis$V12, '7'="연로")
        mdis$V12<- recode_factor(mdis$V12, '8'="심신장애")
        mdis$V12<- recode_factor(mdis$V12, '9'="기타(         )")
        mdis$V13<- recode_factor(mdis$V13, '0'="조사대상아님")
        mdis$V13<- recode_factor(mdis$V13, '1'="있었음")
        mdis$V13<- recode_factor(mdis$V13, '2'="무급가족종사자")
        mdis$V13<- recode_factor(mdis$V13, '3'="없었음")
        mdis$V14<- recode_factor(mdis$V14, '00'="조사대상아님")
        mdis$V14<- recode_factor(mdis$V14, '11'="일시적 병. 사고")
        mdis$V14<- recode_factor(mdis$V14, '12'="연가. 교육")
        mdis$V14<- recode_factor(mdis$V14, '13'="가족적이유")
        mdis$V14<- recode_factor(mdis$V14, '14'="노사분규")
        mdis$V14<- recode_factor(mdis$V14, '15'="조업중단")
        mdis$V14<- recode_factor(mdis$V14, '16'="기타")
        mdis$V14<- recode_factor(mdis$V14, '20'="없었음")
        mdis$V15<- recode_factor(mdis$V15, '0'="조사대상아님")
        mdis$V15<- recode_factor(mdis$V15, '1'="구해보았음")
        mdis$V15<- recode_factor(mdis$V15, '2'="구해보지 않았음")
        mdis$V17<- recode_factor(mdis$V17, '0'="조사대상아님")
        mdis$V17<- recode_factor(mdis$V17, '1'="18시간미만 무급가족종사자")
        mdis$V17<- recode_factor(mdis$V17, '2'="1~35시간")
        mdis$V17<- recode_factor(mdis$V17, '3'="36시간이상")
        mdis$V18<- recode_factor(mdis$V18, '00'="조사대상아님")
        mdis$V18<- recode_factor(mdis$V18, '11'="정규근무시간이 36시간미만")
        mdis$V18<- recode_factor(mdis$V18, '12'="건강")
        mdis$V18<- recode_factor(mdis$V18, '13'="육아")
        mdis$V18<- recode_factor(mdis$V18, '14'="가사")
        mdis$V18<- recode_factor(mdis$V18, '15'="통학")
        mdis$V18<- recode_factor(mdis$V18, '16'="본인이원해서")
        mdis$V18<- recode_factor(mdis$V18, '17'="일거리없어서")
        mdis$V18<- recode_factor(mdis$V18, '18'="기타")
        mdis$V18<- recode_factor(mdis$V18, '21'="일시적 병.사고")
        mdis$V18<- recode_factor(mdis$V18, '22'="일기불순")
        mdis$V18<- recode_factor(mdis$V18, '23'="연가.교육")
        mdis$V18<- recode_factor(mdis$V18, '24'="육아")
        mdis$V18<- recode_factor(mdis$V18, '25'="가족적이유")
        mdis$V18<- recode_factor(mdis$V18, '26'="노사분규")
        mdis$V18<- recode_factor(mdis$V18, '27'="사업부진")
        mdis$V18<- recode_factor(mdis$V18, '28'="기타")
        mdis$V19<- recode_factor(mdis$V19, '0'="조사대상아님")
        mdis$V19<- recode_factor(mdis$V19, '1'="현재하고있는 일의 시간 늘리고싶음")
        mdis$V19<- recode_factor(mdis$V19, '2'="현재하고있는 일이외에 다른 일도 하고싶음")
        mdis$V19<- recode_factor(mdis$V19, '3'="더 많이 일할수있는일로 바꾸고싶음")
        mdis$V19<- recode_factor(mdis$V19, '4'="계속 그대로 일하고싶음")
        mdis$V20<- recode_factor(mdis$V20, '0'="조사대상아님")
        mdis$V20<- recode_factor(mdis$V20, '1'="있었음")
        mdis$V20<- recode_factor(mdis$V20, '2'="없었음")
        mdis$V21<- recode_factor(mdis$V21, '0'="조사대상아님")
        mdis$V21<- recode_factor(mdis$V21, '1'="직업소개소에등록")
        mdis$V21<- recode_factor(mdis$V21, '2'="취직시험")
        mdis$V21<- recode_factor(mdis$V21, '3'="신문.잡지.PC.벽보.등 구인. 구직정보")
        mdis$V21<- recode_factor(mdis$V21, '4'="학교.학원 추천")
        mdis$V21<- recode_factor(mdis$V21, '5'="사업체 방문")
        mdis$V21<- recode_factor(mdis$V21, '6'="친구.친지 소개")
        mdis$V21<- recode_factor(mdis$V21, '7'="자영업준비")
        mdis$V21<- recode_factor(mdis$V21, '8'="기타(         )")
        mdis$V23<- recode_factor(mdis$V23, '0'="조사대상아님")
        mdis$V23<- recode_factor(mdis$V23, '1'="임금근로")
        mdis$V23<- recode_factor(mdis$V23, '2'="비인금근로")
        mdis$V24<- recode_factor(mdis$V24, '0'="조사대상아님")
        mdis$V24<- recode_factor(mdis$V24, '1'="주로하는일")
        mdis$V24<- recode_factor(mdis$V24, '2'="틈틈이 하는일")
        mdis$V25<- recode_factor(mdis$V25, '0'="조사대상아님")
        mdis$V25<- recode_factor(mdis$V25, '1'="하겠음")
        mdis$V25<- recode_factor(mdis$V25, '2'="하지 않겠음")
        mdis$V26<- recode_factor(mdis$V26, '0'="조사대상아님")
        mdis$V26<- recode_factor(mdis$V26, '1'="1년미만")
        mdis$V26<- recode_factor(mdis$V26, '2'="1년이상")
        mdis$V26<- recode_factor(mdis$V26, '3'="없었음")
        mdis$V27<- recode_factor(mdis$V27, '0'="조사대상아님")
        mdis$V27<- recode_factor(mdis$V27, '1'="개인.가족적 이유로")
        mdis$V27<- recode_factor(mdis$V27, '2'="건강상 이유로")
        mdis$V27<- recode_factor(mdis$V27, '3'="정년퇴직, 연로")
        mdis$V27<- recode_factor(mdis$V27, '4'="작업여건(시간.보수 등) 불만족")
        mdis$V27<- recode_factor(mdis$V27, '5'="직장의 휴업, 폐업")
        mdis$V27<- recode_factor(mdis$V27, '6'="명예. 조기퇴직, 정리해고")
        mdis$V27<- recode_factor(mdis$V27, '7'="임시적 또는 계절적 일의 완료")
        mdis$V27<- recode_factor(mdis$V27, '8'="일거리가 없어서 또는 사업경영 악화")
        mdis$V27<- recode_factor(mdis$V27, '9'="기타(         )")
        mdis$V30<- recode_factor(mdis$V30, '0'="조사대상아님")
        mdis$V30<- recode_factor(mdis$V30, '1'="상용 ")
        mdis$V30<- recode_factor(mdis$V30, '2'="임시")
        mdis$V30<- recode_factor(mdis$V30, '3'="일용 ")
        mdis$V30<- recode_factor(mdis$V30, '4'="고용주")
        mdis$V30<- recode_factor(mdis$V30, '5'="자영자")
        mdis$V30<- recode_factor(mdis$V30, '6'="무급가족종사자")
        mdis$V34<- recode_factor(mdis$V34, '1'="농가")
        mdis$V34<- recode_factor(mdis$V34, '2'="비농가")
        mdis$V35<- recode_factor(mdis$V35, '1'="시부")
        mdis$V35<- recode_factor(mdis$V35, '2'="군부")
        mdis$V36<- recode_factor(mdis$V36, '1'="취업자")
        mdis$V36<- recode_factor(mdis$V36, '2'="실업자")
        mdis$V36<- recode_factor(mdis$V36, '3'="비경제활동인구")
        mdis$V37<- recode_factor(mdis$V37, '0'="무학")
        mdis$V37<- recode_factor(mdis$V37, '1'="초등학교")
        mdis$V37<- recode_factor(mdis$V37, '2'="중학교")
        mdis$V37<- recode_factor(mdis$V37, '3'="고등학교")
        mdis$V37<- recode_factor(mdis$V37, '4'="전문대(초급대)")
        mdis$V37<- recode_factor(mdis$V37, '5'="대학")
        mdis$V37<- recode_factor(mdis$V37, '6'="대학원")
        mdis$V38<- recode_factor(mdis$V38, '0'="조사대상아님")
        mdis$V38<- recode_factor(mdis$V38, '1'="인문사회계열")
        mdis$V38<- recode_factor(mdis$V38, '2'="예체능계열")
        mdis$V38<- recode_factor(mdis$V38, '3'="사범계열")
        mdis$V38<- recode_factor(mdis$V38, '4'="기타(상농공수산계열)")
        mdis$V38<- recode_factor(mdis$V38, '5'="자연계열")
        mdis$V38<- recode_factor(mdis$V38, '6'="의약계열")
        mdis$V39<- recode_factor(mdis$V39, '0'="조사대상아님")
        mdis$V39<- recode_factor(mdis$V39, '1'="졸업")
        mdis$V39<- recode_factor(mdis$V39, '2'="재학")
        mdis$V39<- recode_factor(mdis$V39, '3'="중퇴")
        mdis$V39<- recode_factor(mdis$V39, '4'="휴학")

colnames(mdis) = c("1 가구일련번호"
, "가구원번호", "2 가구주관계", "3 성별", "연령", "연령계층", "4-1 출생 년", "4-2 출생 월", "5-1 교육정도(학력)", "5-2 교육정도(수학여부)", "6 혼인상태", "7 활동상태", "8 취업여부", "9 일시휴직여부", "10 1주간 구직여부", "12-1 취업시간", "12-2 취업구분", "13 평소취업시간 및 이유", "14 추가취업 및 전직희망", "15 취업가능성", "16 구직경로"
, "17 구직기간", "18 희망고용형태", "19 희망근무형태", "20 취업의사유무", "25 직장을 그만둔 시기", "26 직장을 그만둔 이유", "27 산업", "28 직업", "29 종사상지위", "조사 년", "조사 월", "조사 일", "가구구분", "시/군부", "경제활동분류", "교육정도(학력)", "교육정도(계열)", "교육정도(수학여부)", "승수(9999999V.999)")

