#**********************************************************************  
#	*주의 사항
#		현재 스크립트 파일은 파일명만 출력되어 있습니다.
#		따라서, 저장된 추출 결과 파일의 경로를 'read.table' 또는 'read.fwf'에 추가하여야 합니다.
#	예) 다운로드 받은 폴더명 : C:\Download
#	  ※ 파일 경로 추가 : "[다운로드 받은 폴더명]\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt"
# 		read.table("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#		또는
#		read.fwf("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#
#		R 스크립트는 R 에서 파일 경로만 수정하시면 바로 실행(Ctrl+Alt+R)가능하며,
#		데이터셋 생성 후에 R 의 여러 가지 분석 기능을 사용할 수 있습니다.
#
#**********************************************************************

install.packages("dplyr")
library(dplyr)

mdis <- read.table("2016_가구마스터_20251107_42394.csv", header=FALSE, sep=",", colClasses = c("character"
, "character", "character", "numeric", "numeric", "numeric", "character", "character", "numeric", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "numeric"
, "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character"
, "character", "character", "character", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"
, "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"
, "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"
, "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"
, "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"
, "numeric", "numeric", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "numeric"
, "character", "character", "character", "character", "numeric", "numeric", "numeric", "character", "numeric", "character", "character", "character", "character"), skip=1, na.string=c("*","**","***","****","*****","******","*******","********","*********","**********","."))

        mdis$V3<- recode_factor(mdis$V3, 'F'="금융부문")
        mdis$V3<- recode_factor(mdis$V3, 'P'="복지부문")
        mdis$V7<- recode_factor(mdis$V7, 'G1'="수도권")
        mdis$V7<- recode_factor(mdis$V7, 'G2'="비수도권")
        mdis$V8<- recode_factor(mdis$V8, '1'="남자")
        mdis$V8<- recode_factor(mdis$V8, '2'="여자")
        mdis$V10<- recode_factor(mdis$V10, 'G1'="노인가구(모든 가구원의 연령이 65세 이상인 가구)")
        mdis$V10<- recode_factor(mdis$V10, 'G2'="그 외 가구")
        mdis$V11<- recode_factor(mdis$V11, 'G1'="조손가구(조부모 가구주와 부모없이 18세 미만 손자녀로 이루어진 가구)")
        mdis$V11<- recode_factor(mdis$V11, 'G2'="그 외 가구")
        mdis$V12<- recode_factor(mdis$V12, 'G1'="한부모 가구(부모가 한 명이고 18세 미만 미혼자녀가 있는 가구)")
        mdis$V12<- recode_factor(mdis$V12, 'G2'="그 외 가구")
        mdis$V13<- recode_factor(mdis$V13, 'G1'="다문화 가구(귀화·인지에 따른 국적취득자 또는 외국인인 가구원이 있는 가구)")
        mdis$V13<- recode_factor(mdis$V13, 'G2'="그 외 가구")
        mdis$V14<- recode_factor(mdis$V14, 'G1'="장애인가구(읍·면사무소, 동주민센터에 장애인으로 등록된 가구원이 있는 가구)")
        mdis$V14<- recode_factor(mdis$V14, 'G2'="그 외 가구")
        mdis$V15<- recode_factor(mdis$V15, '1'="안 받음(미취학 포함)")
        mdis$V15<- recode_factor(mdis$V15, '2'="초등학교")
        mdis$V15<- recode_factor(mdis$V15, '3'="중학교")
        mdis$V15<- recode_factor(mdis$V15, '4'="고등학교")
        mdis$V15<- recode_factor(mdis$V15, '5'="대학(3년제 이하)")
        mdis$V15<- recode_factor(mdis$V15, '6'="대학교(4년제 이상)")
        mdis$V15<- recode_factor(mdis$V15, '7'="대학원 이상")
        mdis$V16<- recode_factor(mdis$V16, '1'="졸업")
        mdis$V16<- recode_factor(mdis$V16, '2'="재학")
        mdis$V16<- recode_factor(mdis$V16, '3'="휴학")
        mdis$V16<- recode_factor(mdis$V16, '4'="중퇴(수료 포함)")
        mdis$V17<- recode_factor(mdis$V17, 'G1'="초등학교 졸업")
        mdis$V17<- recode_factor(mdis$V17, 'G2'="중학교 졸업")
        mdis$V17<- recode_factor(mdis$V17, 'G3'="고등학교 졸업")
        mdis$V17<- recode_factor(mdis$V17, 'G4'="대학졸업 이상")
        mdis$V18<- recode_factor(mdis$V18, '1'="1인 가구")
        mdis$V18<- recode_factor(mdis$V18, '2'="같이 살고 있음")
        mdis$V18<- recode_factor(mdis$V18, '3'="따로 살고 있음(직장)")
        mdis$V18<- recode_factor(mdis$V18, '4'="따로 살고 있음(학업 등)")
        mdis$V19<- recode_factor(mdis$V19, 'A'="농업, 임업 및 어업")
        mdis$V19<- recode_factor(mdis$V19, 'B'="광업")
        mdis$V19<- recode_factor(mdis$V19, 'C'="제조업")
        mdis$V19<- recode_factor(mdis$V19, 'D'="전기, 가스, 증기 및 수도사업")
        mdis$V19<- recode_factor(mdis$V19, 'E'="하수 · 폐기물 처리, 원료재생 및 환경복원업")
        mdis$V19<- recode_factor(mdis$V19, 'F'="건설업")
        mdis$V19<- recode_factor(mdis$V19, 'G'="도매 및 소매업")
        mdis$V19<- recode_factor(mdis$V19, 'H'="운수업")
        mdis$V19<- recode_factor(mdis$V19, 'I'="숙박 및 음식점업")
        mdis$V19<- recode_factor(mdis$V19, 'J'="출판, 영상, 방송통신 및 정보서비스업")
        mdis$V19<- recode_factor(mdis$V19, 'K'="금융 및 보험업")
        mdis$V19<- recode_factor(mdis$V19, 'L'="부동산업 및 임대업")
        mdis$V19<- recode_factor(mdis$V19, 'M'="전문, 과학 및 기술 서비스업")
        mdis$V19<- recode_factor(mdis$V19, 'N'="사업시설관리 및 사업지원 서비스업")
        mdis$V19<- recode_factor(mdis$V19, 'O'="공공행정, 국방 및 사회보장 행정")
        mdis$V19<- recode_factor(mdis$V19, 'P'="교육 서비스업")
        mdis$V19<- recode_factor(mdis$V19, 'Q'="보건업 및 사회복지 서비스업")
        mdis$V19<- recode_factor(mdis$V19, 'R'="예술, 스포츠 및 여가관련 서비스업")
        mdis$V19<- recode_factor(mdis$V19, 'S'="협회 및 단체, 수리  및 기타 개인 서비스업")
        mdis$V19<- recode_factor(mdis$V19, 'T'="가구내 고용활동 및 달리 분류되지 않은 자가소비 생산활동")
        mdis$V19<- recode_factor(mdis$V19, 'U'="국제 및 외국기관")
        mdis$V20<- recode_factor(mdis$V20, '1'="관리자")
        mdis$V20<- recode_factor(mdis$V20, '2'="전문가 및 관련 종사자")
        mdis$V20<- recode_factor(mdis$V20, '3'="사무 종사자")
        mdis$V20<- recode_factor(mdis$V20, '4'="서비스 종사자")
        mdis$V20<- recode_factor(mdis$V20, '5'="판매 종사자")
        mdis$V20<- recode_factor(mdis$V20, '6'="농림어업숙련종사자")
        mdis$V20<- recode_factor(mdis$V20, '7'="기능원 및 관련기능 종사자")
        mdis$V20<- recode_factor(mdis$V20, '8'="장치,기계조작 및 조립 종사자")
        mdis$V20<- recode_factor(mdis$V20, '9'="단순노무 종사자")
        mdis$V20<- recode_factor(mdis$V20, 'A'="군인")
        mdis$V22<- recode_factor(mdis$V22, 'G1'="30세 미만")
        mdis$V22<- recode_factor(mdis$V22, 'G2'="30~40세 미만")
        mdis$V22<- recode_factor(mdis$V22, 'G3'="40~50세 미만")
        mdis$V22<- recode_factor(mdis$V22, 'G4'="50~60세 미만")
        mdis$V22<- recode_factor(mdis$V22, 'G5'="60세이상")
        mdis$V23<- recode_factor(mdis$V23, '1'="상용근로자")
        mdis$V23<- recode_factor(mdis$V23, '2'="임시.일용근로자")
        mdis$V23<- recode_factor(mdis$V23, '3'="고용원이 있는 자영업자")
        mdis$V23<- recode_factor(mdis$V23, '4'="고용원이 없는 자영업자")
        mdis$V23<- recode_factor(mdis$V23, '5'="무급가족종사자")
        mdis$V23<- recode_factor(mdis$V23, '6'="기타 종사자(실적급의 보험설계사, 대리 운전기사, 학습지 방문 교사 등)")
        mdis$V23<- recode_factor(mdis$V23, '7'="기타(무직자, 가사, 학생 등)")
        mdis$V24<- recode_factor(mdis$V24, 'G1'="상용근로자")
        mdis$V24<- recode_factor(mdis$V24, 'G2'="임시 일용 근로자")
        mdis$V24<- recode_factor(mdis$V24, 'G3'="자영자")
        mdis$V24<- recode_factor(mdis$V24, 'G4'="무직 등")
        mdis$V25<- recode_factor(mdis$V25, '1'="미혼")
        mdis$V25<- recode_factor(mdis$V25, '2'="배우자있음")
        mdis$V25<- recode_factor(mdis$V25, '3'="사별")
        mdis$V25<- recode_factor(mdis$V25, '4'="이혼")
        mdis$V26<- recode_factor(mdis$V26, '1'="자기집")
        mdis$V26<- recode_factor(mdis$V26, '2'="전세")
        mdis$V26<- recode_factor(mdis$V26, '3'="보증금 있는 월세")
        mdis$V26<- recode_factor(mdis$V26, '4'="보증금 없는 월세")
        mdis$V26<- recode_factor(mdis$V26, '5'="기타")
        mdis$V27<- recode_factor(mdis$V27, 'G1'="자기집")
        mdis$V27<- recode_factor(mdis$V27, 'G2'="전세")
        mdis$V27<- recode_factor(mdis$V27, 'G3'="월세")
        mdis$V27<- recode_factor(mdis$V27, 'G4'="기타")
        mdis$V28<- recode_factor(mdis$V28, 'G1'="자기집")
        mdis$V28<- recode_factor(mdis$V28, 'G2'="전세")
        mdis$V28<- recode_factor(mdis$V28, 'G3'="월세")
        mdis$V28<- recode_factor(mdis$V28, 'G4'="기타")
        mdis$V29<- recode_factor(mdis$V29, 'G1'="49.6㎡ 미만")
        mdis$V29<- recode_factor(mdis$V29, 'G2'="49.6㎡ ~ 86.0㎡ 미만")
        mdis$V29<- recode_factor(mdis$V29, 'G3'="86.0㎡ ~ 132.2㎡ 미만")
        mdis$V29<- recode_factor(mdis$V29, 'G4'="132.2㎡ 이상")
        mdis$V30<- recode_factor(mdis$V30, 'G1'="단독주택")
        mdis$V30<- recode_factor(mdis$V30, 'G2'="아파트")
        mdis$V30<- recode_factor(mdis$V30, 'G3'="연립 및 다세대")
        mdis$V30<- recode_factor(mdis$V30, 'G4'="기타")
        mdis$V31<- recode_factor(mdis$V31, 'G1'="부채 보유")
        mdis$V31<- recode_factor(mdis$V31, 'G2'="부채 미보유")
        mdis$V32<- recode_factor(mdis$V32, 'Q1'="소득1분위")
        mdis$V32<- recode_factor(mdis$V32, 'Q2'="소득2분위")
        mdis$V32<- recode_factor(mdis$V32, 'Q3'="소득3분위")
        mdis$V32<- recode_factor(mdis$V32, 'Q4'="소득4분위")
        mdis$V32<- recode_factor(mdis$V32, 'Q5'="소득5분위")
        mdis$V33<- recode_factor(mdis$V33, 'Q1'="소득1분위")
        mdis$V33<- recode_factor(mdis$V33, 'Q2'="소득2분위")
        mdis$V33<- recode_factor(mdis$V33, 'Q3'="소득3분위")
        mdis$V33<- recode_factor(mdis$V33, 'Q4'="소득4분위")
        mdis$V33<- recode_factor(mdis$V33, 'Q5'="소득5분위")
        mdis$V34<- recode_factor(mdis$V34, 'Q1'="소득1분위")
        mdis$V34<- recode_factor(mdis$V34, 'Q2'="소득2분위")
        mdis$V34<- recode_factor(mdis$V34, 'Q3'="소득3분위")
        mdis$V34<- recode_factor(mdis$V34, 'Q4'="소득4분위")
        mdis$V34<- recode_factor(mdis$V34, 'Q5'="소득5분위")
        mdis$V35<- recode_factor(mdis$V35, 'D01'="소득1분위")
        mdis$V35<- recode_factor(mdis$V35, 'D02'="소득2분위")
        mdis$V35<- recode_factor(mdis$V35, 'D03'="소득3분위")
        mdis$V35<- recode_factor(mdis$V35, 'D04'="소득4분위")
        mdis$V35<- recode_factor(mdis$V35, 'D05'="소득5분위")
        mdis$V35<- recode_factor(mdis$V35, 'D06'="소득6분위")
        mdis$V35<- recode_factor(mdis$V35, 'D07'="소득7분위")
        mdis$V35<- recode_factor(mdis$V35, 'D08'="소득8분위")
        mdis$V35<- recode_factor(mdis$V35, 'D09'="소득9분위")
        mdis$V35<- recode_factor(mdis$V35, 'D10'="소득10분위")
        mdis$V36<- recode_factor(mdis$V36, 'G1'="1,000만원 미만")
        mdis$V36<- recode_factor(mdis$V36, 'G2'="1,000만원~3,000만원 미만")
        mdis$V36<- recode_factor(mdis$V36, 'G3'="3,000만원~5,000만원 미만")
        mdis$V36<- recode_factor(mdis$V36, 'G4'="5,000만원~7,000만원 미만")
        mdis$V36<- recode_factor(mdis$V36, 'G5'="7,000만원~10,000만원 미만")
        mdis$V36<- recode_factor(mdis$V36, 'G6'="10,000만원 이상")
        mdis$V37<- recode_factor(mdis$V37, 'Q1'="자산1분위")
        mdis$V37<- recode_factor(mdis$V37, 'Q2'="자산2분위")
        mdis$V37<- recode_factor(mdis$V37, 'Q3'="자산3분위")
        mdis$V37<- recode_factor(mdis$V37, 'Q4'="자산4분위")
        mdis$V37<- recode_factor(mdis$V37, 'Q5'="자산5분위")
        mdis$V38<- recode_factor(mdis$V38, 'Q1'="자산1분위")
        mdis$V38<- recode_factor(mdis$V38, 'Q2'="자산2분위")
        mdis$V38<- recode_factor(mdis$V38, 'Q3'="자산3분위")
        mdis$V38<- recode_factor(mdis$V38, 'Q4'="자산4분위")
        mdis$V38<- recode_factor(mdis$V38, 'Q5'="자산5분위")
        mdis$V39<- recode_factor(mdis$V39, 'Q1'="자산1분위")
        mdis$V39<- recode_factor(mdis$V39, 'Q2'="자산2분위")
        mdis$V39<- recode_factor(mdis$V39, 'Q3'="자산3분위")
        mdis$V39<- recode_factor(mdis$V39, 'Q4'="자산4분위")
        mdis$V39<- recode_factor(mdis$V39, 'Q5'="자산5분위")
        mdis$V40<- recode_factor(mdis$V40, 'D01'="자산1분위")
        mdis$V40<- recode_factor(mdis$V40, 'D02'="자산2분위")
        mdis$V40<- recode_factor(mdis$V40, 'D03'="자산3분위")
        mdis$V40<- recode_factor(mdis$V40, 'D04'="자산4분위")
        mdis$V40<- recode_factor(mdis$V40, 'D05'="자산5분위")
        mdis$V40<- recode_factor(mdis$V40, 'D06'="자산6분위")
        mdis$V40<- recode_factor(mdis$V40, 'D07'="자산7분위")
        mdis$V40<- recode_factor(mdis$V40, 'D08'="자산8분위")
        mdis$V40<- recode_factor(mdis$V40, 'D09'="자산9분위")
        mdis$V40<- recode_factor(mdis$V40, 'D10'="자산10분위")
        mdis$V41<- recode_factor(mdis$V41, 'Q1'="순자산1분위")
        mdis$V41<- recode_factor(mdis$V41, 'Q2'="순자산2분위")
        mdis$V41<- recode_factor(mdis$V41, 'Q3'="순자산3분위")
        mdis$V41<- recode_factor(mdis$V41, 'Q4'="순자산4분위")
        mdis$V41<- recode_factor(mdis$V41, 'Q5'="순자산5분위")
        mdis$V42<- recode_factor(mdis$V42, 'Q1'="순자산1분위")
        mdis$V42<- recode_factor(mdis$V42, 'Q2'="순자산2분위")
        mdis$V42<- recode_factor(mdis$V42, 'Q3'="순자산3분위")
        mdis$V42<- recode_factor(mdis$V42, 'Q4'="순자산4분위")
        mdis$V42<- recode_factor(mdis$V42, 'Q5'="순자산5분위")
        mdis$V43<- recode_factor(mdis$V43, 'Q1'="순자산1분위")
        mdis$V43<- recode_factor(mdis$V43, 'Q2'="순자산2분위")
        mdis$V43<- recode_factor(mdis$V43, 'Q3'="순자산3분위")
        mdis$V43<- recode_factor(mdis$V43, 'Q4'="순자산4분위")
        mdis$V43<- recode_factor(mdis$V43, 'Q5'="순자산5분위")
        mdis$V44<- recode_factor(mdis$V44, 'D01'="순자산1분위")
        mdis$V44<- recode_factor(mdis$V44, 'D02'="순자산2분위")
        mdis$V44<- recode_factor(mdis$V44, 'D03'="순자산3분위")
        mdis$V44<- recode_factor(mdis$V44, 'D04'="순자산4분위")
        mdis$V44<- recode_factor(mdis$V44, 'D05'="순자산5분위")
        mdis$V44<- recode_factor(mdis$V44, 'D06'="순자산6분위")
        mdis$V44<- recode_factor(mdis$V44, 'D07'="순자산7분위")
        mdis$V44<- recode_factor(mdis$V44, 'D08'="순자산8분위")
        mdis$V44<- recode_factor(mdis$V44, 'D09'="순자산9분위")
        mdis$V44<- recode_factor(mdis$V44, 'D10'="순자산10분위")
        mdis$V144<- recode_factor(mdis$V144, '1'="저축과 금융자산 투자")
        mdis$V144<- recode_factor(mdis$V144, '2'="부동산 구입")
        mdis$V144<- recode_factor(mdis$V144, '3'="부채 상환")
        mdis$V144<- recode_factor(mdis$V144, '4'="내구재(자동차, 가구 등) 구입")
        mdis$V144<- recode_factor(mdis$V144, '5'="기타")
        mdis$V145<- recode_factor(mdis$V145, '1'="주택구입 및 전세.월세보증금")
        mdis$V145<- recode_factor(mdis$V145, '2'="노후대책")
        mdis$V145<- recode_factor(mdis$V145, '3'="결혼자금마련")
        mdis$V145<- recode_factor(mdis$V145, '4'="사고 및 질병대비")
        mdis$V145<- recode_factor(mdis$V145, '5'="자녀교육비")
        mdis$V145<- recode_factor(mdis$V145, '6'="부채 상환")
        mdis$V145<- recode_factor(mdis$V145, '7'="자동차 등 내구재 구입")
        mdis$V145<- recode_factor(mdis$V145, '8'="여행 등 여가")
        mdis$V145<- recode_factor(mdis$V145, '9'="상속 및 증여")
        mdis$V145<- recode_factor(mdis$V145, '10'="창업 및 사업 확장")
        mdis$V145<- recode_factor(mdis$V145, '11'="기타(     )")
        mdis$V146<- recode_factor(mdis$V146, '1'="은행 예금")
        mdis$V146<- recode_factor(mdis$V146, '2'="저축은행 예금")
        mdis$V146<- recode_factor(mdis$V146, '3'="비은행금융기관 예금")
        mdis$V146<- recode_factor(mdis$V146, '4'="개인연금")
        mdis$V146<- recode_factor(mdis$V146, '5'="보험")
        mdis$V146<- recode_factor(mdis$V146, '6'="채권(직접투자)")
        mdis$V146<- recode_factor(mdis$V146, '7'="주식(직접투자)")
        mdis$V146<- recode_factor(mdis$V146, '8'="수익증권(펀드 등 간접투자)")
        mdis$V146<- recode_factor(mdis$V146, '9'="계(契)")
        mdis$V146<- recode_factor(mdis$V146, '10'="기타(     )")
        mdis$V147<- recode_factor(mdis$V147, '1'="수익성")
        mdis$V147<- recode_factor(mdis$V147, '2'="안전성")
        mdis$V147<- recode_factor(mdis$V147, '3'="현금화 가능성")
        mdis$V147<- recode_factor(mdis$V147, '4'="접근성(이용의 편리성)")
        mdis$V147<- recode_factor(mdis$V147, '5'="기타(     )")
        mdis$V148<- recode_factor(mdis$V148, '1'="하락할 것이다")
        mdis$V148<- recode_factor(mdis$V148, '2'="변화 없을 것이다")
        mdis$V148<- recode_factor(mdis$V148, '3'="상승할 것이다")
        mdis$V148<- recode_factor(mdis$V148, '4'="모르겠다")
        mdis$V149<- recode_factor(mdis$V149, '1'="예")
        mdis$V149<- recode_factor(mdis$V149, '2'="아니오")
        mdis$V150<- recode_factor(mdis$V150, '1'="내집 마련")
        mdis$V150<- recode_factor(mdis$V150, '2'="가치 상승")
        mdis$V150<- recode_factor(mdis$V150, '3'="임대수입")
        mdis$V150<- recode_factor(mdis$V150, '4'="창업 또는 사업장(상가.토지 등)마련")
        mdis$V150<- recode_factor(mdis$V150, '5'="노후대책")
        mdis$V150<- recode_factor(mdis$V150, '6'="가구원용 주택 마련")
        mdis$V150<- recode_factor(mdis$V150, '7'="여행 등 여가")
        mdis$V150<- recode_factor(mdis$V150, '8'="상속 및 증여")
        mdis$V150<- recode_factor(mdis$V150, '9'="기타(     )")
        mdis$V151<- recode_factor(mdis$V151, '1'="단독주택(다가구주택 포함)")
        mdis$V151<- recode_factor(mdis$V151, '2'="아파트")
        mdis$V151<- recode_factor(mdis$V151, '3'="연립 및 다세대주택")
        mdis$V151<- recode_factor(mdis$V151, '4'="건물(상가, 오피스텔, 빌딩 등)")
        mdis$V151<- recode_factor(mdis$V151, '5'="토지(논밭, 임야, 대지 등)")
        mdis$V151<- recode_factor(mdis$V151, '6'="해외 부동산")
        mdis$V151<- recode_factor(mdis$V151, '7'="기타")
        mdis$V152<- recode_factor(mdis$V152, '1'="부동산 가격의 불확실성")
        mdis$V152<- recode_factor(mdis$V152, '2'="세금(종합부동산세 등) 부담")
        mdis$V152<- recode_factor(mdis$V152, '3'="금융자산 등에 투자")
        mdis$V152<- recode_factor(mdis$V152, '4'="부동산에 대한 정보 부족")
        mdis$V152<- recode_factor(mdis$V152, '5'="기타")
        mdis$V153<- recode_factor(mdis$V153, '1'="감소할 것이다")
        mdis$V153<- recode_factor(mdis$V153, '2'="변화 없을 것이다")
        mdis$V153<- recode_factor(mdis$V153, '3'="증가할 것이다")
        mdis$V154<- recode_factor(mdis$V154, '1'="거주주택 마련")
        mdis$V154<- recode_factor(mdis$V154, '2'="거주주택 이외 부동산 마련")
        mdis$V154<- recode_factor(mdis$V154, '3'="전세.월세 보증금 마련")
        mdis$V154<- recode_factor(mdis$V154, '4'="증권투자자금 마련")
        mdis$V154<- recode_factor(mdis$V154, '5'="부채 상환")
        mdis$V154<- recode_factor(mdis$V154, '6'="사업자금(영농자금 포함)마련")
        mdis$V154<- recode_factor(mdis$V154, '7'="결혼 자금 마련")
        mdis$V154<- recode_factor(mdis$V154, '8'="의료비 마련")
        mdis$V154<- recode_factor(mdis$V154, '9'="교육비 마련")
        mdis$V154<- recode_factor(mdis$V154, '10'="생활비 마련")
        mdis$V154<- recode_factor(mdis$V154, '11'="기타(     )")
        mdis$V155<- recode_factor(mdis$V155, '1'="감소하였다")
        mdis$V155<- recode_factor(mdis$V155, '2'="변화 없었다")
        mdis$V155<- recode_factor(mdis$V155, '3'="증가하였다")
        mdis$V156<- recode_factor(mdis$V156, '1'="소득으로 상환")
        mdis$V156<- recode_factor(mdis$V156, '2'="금융자산 처분 및 퇴직(연)금정산")
        mdis$V156<- recode_factor(mdis$V156, '3'="주거의 변경에 의한 상환")
        mdis$V156<- recode_factor(mdis$V156, '4'="부동산 및 기타 자산 처분(거주주택 제외)")
        mdis$V156<- recode_factor(mdis$V156, '5'="상속 및 증여에 의한 상환")
        mdis$V156<- recode_factor(mdis$V156, '6'="기타(     )")
        mdis$V157<- recode_factor(mdis$V157, '1'="있음")
        mdis$V157<- recode_factor(mdis$V157, '2'="없음")
        mdis$V158<- recode_factor(mdis$V158, '1'="이자 또는 원금상환 부담 상승")
        mdis$V158<- recode_factor(mdis$V158, '2'="자금융통 차질")
        mdis$V158<- recode_factor(mdis$V158, '3'="소득 감소")
        mdis$V158<- recode_factor(mdis$V158, '4'="가계지출 증가")
        mdis$V158<- recode_factor(mdis$V158, '5'="납부기일 착오")
        mdis$V158<- recode_factor(mdis$V158, '6'="기타(     )")
        mdis$V159<- recode_factor(mdis$V159, '1'="부담이 없다")
        mdis$V159<- recode_factor(mdis$V159, '2'="약간 부담스럽다")
        mdis$V159<- recode_factor(mdis$V159, '3'="매우 부담스럽다")
        mdis$V160<- recode_factor(mdis$V160, '1'="있음")
        mdis$V160<- recode_factor(mdis$V160, '2'="없음")
        mdis$V162<- recode_factor(mdis$V162, '1'="줄이고 있음")
        mdis$V162<- recode_factor(mdis$V162, '2'="줄이고 있지 않음")
        mdis$V163<- recode_factor(mdis$V163, '1'="저축 및 금융자산 투자")
        mdis$V163<- recode_factor(mdis$V163, '2'="레저.여가.문화비")
        mdis$V163<- recode_factor(mdis$V163, '3'="식품.외식비")
        mdis$V163<- recode_factor(mdis$V163, '4'="의류구입비")
        mdis$V163<- recode_factor(mdis$V163, '5'="교육비 마련")
        mdis$V163<- recode_factor(mdis$V163, '6'="교통.통신비")
        mdis$V163<- recode_factor(mdis$V163, '7'="내구재구입비")
        mdis$V163<- recode_factor(mdis$V163, '8'="기타(     )")
        mdis$V164<- recode_factor(mdis$V164, '1'="대출기한 내에 갚을 수 있다")
        mdis$V164<- recode_factor(mdis$V164, '2'="대출기한은 경과하더라도 20○○년까지는 갚을 수 있다")
        mdis$V164<- recode_factor(mdis$V164, '3'="상환 불가능할 것이다")
        mdis$V165<- recode_factor(mdis$V165, '1'="은퇴하지 않았다")
        mdis$V165<- recode_factor(mdis$V165, '2'="은퇴하였다")
        mdis$V169<- recode_factor(mdis$V169, '1'="아주 잘 되어 있다")
        mdis$V169<- recode_factor(mdis$V169, '2'="잘 되어 있다")
        mdis$V169<- recode_factor(mdis$V169, '3'="보통이다")
        mdis$V169<- recode_factor(mdis$V169, '4'="잘 되어 있지 않다")
        mdis$V169<- recode_factor(mdis$V169, '5'="전혀 되어 있지 않다")
        mdis$V171<- recode_factor(mdis$V171, '1'="충분히 여유 있다")
        mdis$V171<- recode_factor(mdis$V171, '2'="여유 있다")
        mdis$V171<- recode_factor(mdis$V171, '3'="보통이다")
        mdis$V171<- recode_factor(mdis$V171, '4'="부족하다")
        mdis$V171<- recode_factor(mdis$V171, '5'="매우 부족하다")
        mdis$V172<- recode_factor(mdis$V172, '1'="가족의 수입, 자녀, 친지 등의 용돈")
        mdis$V172<- recode_factor(mdis$V172, '2'="국민연금, 공무원연금 등 공적 연금")
        mdis$V172<- recode_factor(mdis$V172, '3'="개인 저축액 또는 사적연금(이자, 배당금 포함)")
        mdis$V172<- recode_factor(mdis$V172, '4'="공적 수혜금(기초생활보장수급금, 기초연금 등)")
        mdis$V172<- recode_factor(mdis$V172, '5'="연금형 부채(농지연금, 주택연금 등)")
        mdis$V172<- recode_factor(mdis$V172, '6'="임대수입")
        mdis$V172<- recode_factor(mdis$V172, '7'="빌린돈(연금형 부채 제외)")
        mdis$V172<- recode_factor(mdis$V172, '8'="기타")
        mdis$V173<- recode_factor(mdis$V173, '1'="감소할 것이다")
        mdis$V173<- recode_factor(mdis$V173, '2'="변화가 없을 것이다")
        mdis$V173<- recode_factor(mdis$V173, '3'="증가할 것이다")
        mdis$V174<- recode_factor(mdis$V174, '1'="감소할 것이다")
        mdis$V174<- recode_factor(mdis$V174, '2'="변화가 없을 것이다")
        mdis$V174<- recode_factor(mdis$V174, '3'="증가할 것이다")

colnames(mdis) = c("조사연도"
, "MD제공용_가구고유번호", "조사부문코드", "가중값", "금융부문_가중값", "복지부문_가중값", "수도권여부", "가구주_성별코드", "가구원수", "노인가구코드", "조손가구코드", "한부모가구코드", "다문화가구코드", "보완_등록장애인유무_가구구분코드", "가구주_교육정도_학력코드", "가구주_교육정도_수학구분코드", "가구주_교육정도_통합코드", "가구주_동거여부", "가구주_산업대분류코드", "가구주_직업대분류코드", "가구주_만연령"
, "가구주연령_10세단위코드", "가구주_종사상지위코드", "보도용_가구주_종사상지위코드", "가구주_혼인상태코드", "입주형태코드", "입주형태통합코드", "과거기준입주형태통합코드", "전용면적규모코드", "주택종류통합코드", "부채보유여부", "보완_소득5분위코드", "보완_금융부문_소득5분위코드", "보완_복지부문_소득5분위코드", "보완_소득10분위코드", "보도용_보완_소득계층구간코드", "자산총액5분위코드", "금융부문_자산총액5분위코드", "복지부문_자산총액5분위코드", "자산총액10분위코드", "순자산5분위코드"
, "금융부문_순자산5분위코드", "복지부문_순자산5분위코드", "순자산10분위코드", "자산", "자산_금융자산", "자산_금융자산_저축금액", "자산_금융자산_저축_적립예치식저축금액", "자산_금융자산_저축_적립예치식저축_수시적립예치식저축금액", "자산_금융자산_저축_적립예치식저축_저축성보장성보험금액", "자산_금융자산_저축_적립예치식저축_주식채권펀드금액", "자산_금융자산_저축_기타저축금액", "자산_금융자산_현거주지전월세보증금", "자산_실물자산", "자산_실물자산_부동산금액", "자산_실물자산_부동산_거주주택금액", "자산_실물자산_부동산_거주주택이외부동산금액", "자산_실물자산_부동산_계약금중도금납입금액", "자산_실물자산_기타실물자산", "자산_실물자산_기타실물자산_자동차금액", "자산_실물자산_기타실물자산_기타금액"
, "자산_실물자산_기타실물자산_기타_자동차이외기타실물자산", "자산_실물자산_기타실물자산_기타_권리금", "부채", "부채_금융부채", "부채_금융부채_담보대출금액", "부채_금융부채_담보대출_대출용도_거주주택구입금액", "부채_금융부채_담보대출_대출용도_거주주택이외부동산구입금액", "부채_금융부채_담보대출_대출용도_전월세보증금마련금액", "부채_금융부채_담보대출_대출용도_부채상환금액", "부채_금융부채_담보대출_대출용도_사업자금마련금액", "부채_금융부채_담보대출_대출용도_생활비마련금액", "부채_금융부채_담보대출_대출용도_기타용도금액", "부채_금융부채_담보대출_대출기관_은행금액", "부채_금융부채_담보대출_대출기관_저축은행금액", "부채_금융부채_담보대출_대출기관_비은행금융기관금액", "부채_금융부채_담보대출_대출기관_보험회사금액", "부채_금융부채_담보대출_대출기관_기타기관금액", "부채_금융부채_담보대출_상환방법_만기일시금액", "부채_금융부채_담보대출_상환방법_원금분할상환금액", "부채_금융부채_담보대출_상환방법_원리금분할상환금액"
, "부채_금융부채_담보대출_상환방법_원리금분할일부만기상환금액", "부채_금융부채_담보대출_상환방법_기타상환방법금액", "부채_금융부채_담보대출_담보형태_거주주택금액", "부채_금융부채_담보대출_담보형태_거주주택이외부동산금액", "부채_금융부채_담보대출_담보형태_예적금보험펀드채권금액", "부채_금융부채_담보대출_담보형태_기타금액", "부채_금융부채_담보대출_부동산담보대출금액", "부채_금융부채_담보대출_부동산이외담보대출금액", "부채_금융부채_신용대출금액", "부채_금융부채_신용대출_대출용도_거주주택구입금액", "부채_금융부채_신용대출_대출용도_거주주택이외부동산구입금액", "부채_금융부채_신용대출_대출용도_전월세보증금마련금액", "부채_금융부채_신용대출_대출용도_부채상환금액", "부채_금융부채_신용대출_대출용도_사업자금마련금액", "부채_금융부채_신용대출_대출용도_생활비마련금액", "부채_금융부채_신용대출_대출용도_기타용도금액", "부채_금융부채_신용대출_대출기관_은행금액", "부채_금융부채_신용대출_대출기관_저축은행금액", "부채_금융부채_신용대출_대출기관_비은행금융기관금액", "부채_금융부채_신용대출_대출기관_보험회사금액"
, "부채_금융부채_신용대출_대출기관_기타기관금액", "부채_금융부채_신용대출_상환방법_만기일시금액", "부채_금융부채_신용대출_상환방법_원금분할상환금액", "부채_금융부채_신용대출_상환방법_원리금분할상환금액", "부채_금융부채_신용대출_상환방법_원리금분할일부만기상환금액", "부채_금융부채_신용대출_상환방법_기타상환방법금액", "부채_금융부채_신용대출_대출종류_신용대출금액", "부채_금융부채_신용대출_대출종류_마이너스통장금액", "부채_금융부채_신용카드관련대출금액", "부채_금융부채_외상할부미상환금액", "부채_금융부채_계탄후불입금액", "부채_임대보증금", "원리금상환금액", "원리금상환_원금상환금액", "원리금상환_이자지급금액", "순자산", "보완_경상소득", "보완_경상소득_근로소득", "보완_경상소득_사업소득", "보완_경상소득_재산소득"
, "보완_경상소득_공적이전소득", "조사_경상소득_사적이전소득", "보완_경상소득_이전소득", "보완_처분가능소득", "조사_지출비", "보완_지출_비소비지출비", "보완_지출_비소비지출_세금", "보완_지출_비소비지출_공적연금사회보험료", "조사_지출_비소비지출_가구사이이전지출비", "조사2_지출_비소비지출_비영리단체이전지출액", "조사2_지출_비소비지출_연간지급이자", "지출_소비지출비", "지출_소비지출_외식비포함식료품비", "지출_소비지출_주거비", "지출_소비지출_보육료포함교육비", "지출_소비지출_의료비", "지출_소비지출_교통비", "지출_소비지출_통신비", "지출_소비지출_경조비및기타소비지출비", "지출_소비지출_경조비"
, "지출_소비지출_기타소비지출비", "조사_분배6차_균등화처분가능소득", "여유자금운용계획코드", "금융자산투자주목적코드", "금융자산투자운용방법코드", "금융자산투자고려사항코드", "거주지주택가격전망코드", "여유자금부동산투자여부", "부동산투자주목적코드", "투자선호부동산코드", "부동산투자기피사유코드", "1년후금융부채규모전망코드", "부채증가원인코드", "1년전대비부채증감코드", "부채상환방법코드", "원리금연체여부", "원리금연체사유코드", "원리금상환_생계부담정도코드", "30일이상원리금연체여부", "원리금상환_생계부담_소득대비상환액비중"
, "원리금상환_가계지출감소여부", "원리금상환_가계지출감소항목코드", "부채상환가능시기코드", "가구주_은퇴여부", "가구주_미은퇴_은퇴연령", "가구주_미은퇴_최소생활비", "가구주_미은퇴_적정생활비", "가구주_미은퇴_노후준비상황코드", "가구주_은퇴_은퇴연령", "가구주_은퇴_적정생활비충당여부", "가구주_은퇴_생활비재원마련코드", "1년후소득변화코드", "1년후지출변화코드")

