#**********************************************************************  
#	*주의 사항
#		현재 스크립트 파일은 파일명만 출력되어 있습니다.
#		따라서, 저장된 추출 결과 파일의 경로를 'read.table' 또는 'read.fwf'에 추가하여야 합니다.
#	예) 다운로드 받은 폴더명 : C:\Download
#	  ※ 파일 경로 추가 : "[다운로드 받은 폴더명]\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt"
# 		read.table("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#		또는
#		read.fwf("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#
#		R 스크립트는 R 에서 파일 경로만 수정하시면 바로 실행(Ctrl+Alt+R)가능하며,
#		데이터셋 생성 후에 R 의 여러 가지 분석 기능을 사용할 수 있습니다.
#
#**********************************************************************

install.packages("dplyr")
library(dplyr)

mdis <- read.table("1994_경제활동인구조사 연간자료1 (1981-1999)_20250711_21603.csv", header=FALSE, sep=",", colClasses = c("numeric"
, "numeric", "character", "character", "numeric", "character", "numeric", "character", "character", "character", "character", "character", "character", "character", "character", "character", "numeric", "character", "character", "numeric", "character"
, "character", "character", "character", "numeric", "character", "character", "character", "numeric"), skip=1, na.string=c("*","**","***","****","*****","******","*******","********","*********","**********","."))

        mdis$V3<- recode_factor(mdis$V3, '0'="동거인")
        mdis$V3<- recode_factor(mdis$V3, '1'="가구주")
        mdis$V3<- recode_factor(mdis$V3, '2'="배우자")
        mdis$V3<- recode_factor(mdis$V3, '3'="미혼자녀")
        mdis$V3<- recode_factor(mdis$V3, '4'="미혼형제자매")
        mdis$V3<- recode_factor(mdis$V3, '5'="부모(장인, 장모 포함)")
        mdis$V3<- recode_factor(mdis$V3, '6'="조부모")
        mdis$V3<- recode_factor(mdis$V3, '7'="기혼자녀및가족")
        mdis$V3<- recode_factor(mdis$V3, '8'="기혼형제자매및가족")
        mdis$V3<- recode_factor(mdis$V3, '9'="기타 친척")
        mdis$V4<- recode_factor(mdis$V4, '1'="남자")
        mdis$V4<- recode_factor(mdis$V4, '2'="여자")
        mdis$V6<- recode_factor(mdis$V6, '01'="15~19세")
        mdis$V6<- recode_factor(mdis$V6, '02'="20~24세")
        mdis$V6<- recode_factor(mdis$V6, '03'="25~29세")
        mdis$V6<- recode_factor(mdis$V6, '04'="30~34세")
        mdis$V6<- recode_factor(mdis$V6, '05'="35~39세")
        mdis$V6<- recode_factor(mdis$V6, '06'="40~44세")
        mdis$V6<- recode_factor(mdis$V6, '07'="45~49세")
        mdis$V6<- recode_factor(mdis$V6, '08'="50~54세")
        mdis$V6<- recode_factor(mdis$V6, '09'="55~59세")
        mdis$V6<- recode_factor(mdis$V6, '10'="60~64세")
        mdis$V6<- recode_factor(mdis$V6, '11'="65세이상")
        mdis$V8<- recode_factor(mdis$V8, '1'="미혼")
        mdis$V8<- recode_factor(mdis$V8, '2'="배우자있음")
        mdis$V8<- recode_factor(mdis$V8, '3'="사별")
        mdis$V8<- recode_factor(mdis$V8, '4'="이혼")
        mdis$V9<- recode_factor(mdis$V9, '1'="초등학교이하")
        mdis$V9<- recode_factor(mdis$V9, '2'="중학교")
        mdis$V9<- recode_factor(mdis$V9, '3'="고등학교")
        mdis$V9<- recode_factor(mdis$V9, '4'="대학(4년제미만)")
        mdis$V9<- recode_factor(mdis$V9, '5'="대학이상")
        mdis$V10<- recode_factor(mdis$V10, '1'="졸업")
        mdis$V10<- recode_factor(mdis$V10, '2'="재학")
        mdis$V10<- recode_factor(mdis$V10, '3'="중퇴 및 휴학")
        mdis$V11<- recode_factor(mdis$V11, '1'="일하였음")
        mdis$V11<- recode_factor(mdis$V11, '2'="일시휴직")
        mdis$V11<- recode_factor(mdis$V11, '3'="구직활동")
        mdis$V11<- recode_factor(mdis$V11, '4'="가사")
        mdis$V11<- recode_factor(mdis$V11, '5'="육아")
        mdis$V11<- recode_factor(mdis$V11, '6'="통학")
        mdis$V11<- recode_factor(mdis$V11, '7'="연로")
        mdis$V11<- recode_factor(mdis$V11, '8'="심신장애")
        mdis$V11<- recode_factor(mdis$V11, '9'="기타")
        mdis$V12<- recode_factor(mdis$V12, '1'="있었음")
        mdis$V12<- recode_factor(mdis$V12, '2'="없었음")
        mdis$V13<- recode_factor(mdis$V13, '11'="일시적병,사고")
        mdis$V13<- recode_factor(mdis$V13, '12'="연가, 휴가")
        mdis$V13<- recode_factor(mdis$V13, '13'="노동쟁의")
        mdis$V13<- recode_factor(mdis$V13, '14'="조업중단")
        mdis$V13<- recode_factor(mdis$V13, '15'="기타")
        mdis$V13<- recode_factor(mdis$V13, '20'="없었음")
        mdis$V14<- recode_factor(mdis$V14, '1'="구해보았음")
        mdis$V14<- recode_factor(mdis$V14, '2'="불가피한사유로구해보지않았음")
        mdis$V14<- recode_factor(mdis$V14, '3'="구해보지않았음")
        mdis$V15<- recode_factor(mdis$V15, '1'="있었음")
        mdis$V15<- recode_factor(mdis$V15, '2'="없었음")
        mdis$V16<- recode_factor(mdis$V16, '1'="하겠음")
        mdis$V16<- recode_factor(mdis$V16, '2'="하지않겠음")
        mdis$V18<- recode_factor(mdis$V18, '1'="18시간 미만무급가족종사자")
        mdis$V18<- recode_factor(mdis$V18, '2'="1~35시간")
        mdis$V18<- recode_factor(mdis$V18, '3'="36시간 이상")
        mdis$V19<- recode_factor(mdis$V19, '11'="건강")
        mdis$V19<- recode_factor(mdis$V19, '12'="가사,통학")
        mdis$V19<- recode_factor(mdis$V19, '13'="일할필요없어서")
        mdis$V19<- recode_factor(mdis$V19, '14'="일거리가 없어서")
        mdis$V19<- recode_factor(mdis$V19, '15'="기타")
        mdis$V19<- recode_factor(mdis$V19, '21'="일시적병,사고")
        mdis$V19<- recode_factor(mdis$V19, '22'="연가,휴가")
        mdis$V19<- recode_factor(mdis$V19, '23'="조업중단")
        mdis$V19<- recode_factor(mdis$V19, '24'="조업단축")
        mdis$V19<- recode_factor(mdis$V19, '25'="기타")
        mdis$V21<- recode_factor(mdis$V21, '1'="신규실업")
        mdis$V21<- recode_factor(mdis$V21, '2'="보수및작업환경불만족")
        mdis$V21<- recode_factor(mdis$V21, '3'="장래성이없어서")
        mdis$V21<- recode_factor(mdis$V21, '4'="폐업,해고")
        mdis$V21<- recode_factor(mdis$V21, '5'="정년퇴직")
        mdis$V21<- recode_factor(mdis$V21, '6'="자기사업을하려고")
        mdis$V21<- recode_factor(mdis$V21, '7'="사업부진")
        mdis$V21<- recode_factor(mdis$V21, '8'="결혼,육아")
        mdis$V21<- recode_factor(mdis$V21, '9'="기타")
        mdis$V22<- recode_factor(mdis$V22, 'A'="농업 및 임업(01-02)")
        mdis$V22<- recode_factor(mdis$V22, 'B'="어 업(05)")
        mdis$V22<- recode_factor(mdis$V22, 'C'="광 업(10-14)")
        mdis$V22<- recode_factor(mdis$V22, 'D'="제 조 업(15-37)")
        mdis$V22<- recode_factor(mdis$V22, 'E'="전기, 가스 및 수도사업(40-41)")
        mdis$V22<- recode_factor(mdis$V22, 'F'="건설업(45)")
        mdis$V22<- recode_factor(mdis$V22, 'G'="도소매업 및 소비자용품 수리업(50-52)")
        mdis$V22<- recode_factor(mdis$V22, 'H'="숙박 및 음식점업(55)")
        mdis$V22<- recode_factor(mdis$V22, 'I'="운수업 및 통신업(60-64)")
        mdis$V22<- recode_factor(mdis$V22, 'J'="금융 및 보험업(65-67)")
        mdis$V22<- recode_factor(mdis$V22, 'K'="부동산업 및 임대업 및 사업서비스업(70-74)")
        mdis$V22<- recode_factor(mdis$V22, 'L'="공공행정, 국방 및 사회보장행정(75)")
        mdis$V22<- recode_factor(mdis$V22, 'M'="교육 서비스업(80)")
        mdis$V22<- recode_factor(mdis$V22, 'N'="보건 및 사회복지사업(85)")
        mdis$V22<- recode_factor(mdis$V22, 'O'="기타 공공, 수리 및 개인서비스업(90-93)")
        mdis$V22<- recode_factor(mdis$V22, 'P'="가사 서비스업(95)")
        mdis$V22<- recode_factor(mdis$V22, 'Q'="국제 및 외국기관(99)")
        mdis$V23<- recode_factor(mdis$V23, '1'="입법공무원,고위임직원 및 관리자")
        mdis$V23<- recode_factor(mdis$V23, '2'="전문가")
        mdis$V23<- recode_factor(mdis$V23, '3'="기술공 및 준전문가")
        mdis$V23<- recode_factor(mdis$V23, '4'="사무직원")
        mdis$V23<- recode_factor(mdis$V23, '5'="서비스근로자 및 상점과 시장판매 근로자")
        mdis$V23<- recode_factor(mdis$V23, '6'="농업 및 어업숙련 근로자")
        mdis$V23<- recode_factor(mdis$V23, '7'="기능원 및 관련 기능근로자")
        mdis$V23<- recode_factor(mdis$V23, '8'="장치, 기계조작원  및  조립원")
        mdis$V23<- recode_factor(mdis$V23, '9'="단순노무직 종사자")
        mdis$V24<- recode_factor(mdis$V24, '11'="고용주")
        mdis$V24<- recode_factor(mdis$V24, '12'="자영자")
        mdis$V24<- recode_factor(mdis$V24, '13'="무급가족종사자")
        mdis$V24<- recode_factor(mdis$V24, '21'="상용근로자")
        mdis$V24<- recode_factor(mdis$V24, '22'="임시근로자")
        mdis$V24<- recode_factor(mdis$V24, '23'="일용근로자")
        mdis$V26<- recode_factor(mdis$V26, '11'="취업자")
        mdis$V26<- recode_factor(mdis$V26, '12'="일시휴직자")
        mdis$V26<- recode_factor(mdis$V26, '21'="신규실업자")
        mdis$V26<- recode_factor(mdis$V26, '22'="전직실업자")
        mdis$V26<- recode_factor(mdis$V26, '31'="구직경험자")
        mdis$V26<- recode_factor(mdis$V26, '32'="6개월내구직자")
        mdis$V26<- recode_factor(mdis$V26, '33'="6개월내비구직자")
        mdis$V26<- recode_factor(mdis$V26, '34'="순수비경제활동인구")
        mdis$V27<- recode_factor(mdis$V27, '1'="농가")
        mdis$V27<- recode_factor(mdis$V27, '2'="비농가")
        mdis$V28<- recode_factor(mdis$V28, '1'="동부")
        mdis$V28<- recode_factor(mdis$V28, '2'="읍부")

colnames(mdis) = c("1.가구일련번호"
, "가구원일련번호", "2.가구주와의관계", "3.성별", "만연령", "연령계층", "4.생년월", "6.혼인상태", "5-1.교육정도(학력)", "5-2.교육정도(수학여부)", "7.활동상태", "8.취업여부", "9.일시휴직이유", "10.1주간구직활동", "11.취업가능성여부", "12.취업의사유무", "가-1-1.취업시간", "가-1-2.취업구분", "가-2.1주일36시간미만일할경우", "나-2.구직기간", "나-3.전직유무및실업동기"
, "라-1.산업", "라-2.직업", "라-3.종사상지위", "조사년월일", "경제활동분류", "가구구분", "동부/읍부", "가중값")

