#**********************************************************************  
#	*주의 사항
#		현재 스크립트 파일은 파일명만 출력되어 있습니다.
#		따라서, 저장된 추출 결과 파일의 경로를 'read.table' 또는 'read.fwf'에 추가하여야 합니다.
#	예) 다운로드 받은 폴더명 : C:\Download
#	  ※ 파일 경로 추가 : "[다운로드 받은 폴더명]\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt"
# 		read.table("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#		또는
#		read.fwf("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#
#		R 스크립트는 R 에서 파일 경로만 수정하시면 바로 실행(Ctrl+Alt+R)가능하며,
#		데이터셋 생성 후에 R 의 여러 가지 분석 기능을 사용할 수 있습니다.
#
#**********************************************************************

install.packages("dplyr")
library(dplyr)

mdis <- read.table("2000_경제활동인구조사 연간자료2 (2000~)_20250518_80427.csv", header=FALSE, sep=",", colClasses = c("character"
, "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "numeric", "character", "character", "character", "character", "character", "numeric", "character"
, "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "numeric", "character", "character", "character", "numeric", "character", "character"
, "character", "character"), skip=1, na.string=c("*","**","***","****","*****","******","*******","********","*********","**********","."))

        mdis$V2<- recode_factor(mdis$V2, '1'="가구주")
        mdis$V2<- recode_factor(mdis$V2, '2'="배우자")
        mdis$V2<- recode_factor(mdis$V2, '3'="미혼자녀")
        mdis$V2<- recode_factor(mdis$V2, '4'="기혼자녀")
        mdis$V2<- recode_factor(mdis$V2, '5'="손자녀")
        mdis$V2<- recode_factor(mdis$V2, '6'="부모")
        mdis$V2<- recode_factor(mdis$V2, '7'="조부모")
        mdis$V2<- recode_factor(mdis$V2, '8'="미혼형제자매")
        mdis$V2<- recode_factor(mdis$V2, '9'="기타")
        mdis$V3<- recode_factor(mdis$V3, '1'="남자")
        mdis$V3<- recode_factor(mdis$V3, '2'="여자")
        mdis$V5<- recode_factor(mdis$V5, '0'="무학")
        mdis$V5<- recode_factor(mdis$V5, '1'="초등학교")
        mdis$V5<- recode_factor(mdis$V5, '2'="중학교")
        mdis$V5<- recode_factor(mdis$V5, '3'="고등학교")
        mdis$V5<- recode_factor(mdis$V5, '4'="전문대(초급대)")
        mdis$V5<- recode_factor(mdis$V5, '5'="대학")
        mdis$V5<- recode_factor(mdis$V5, '6'="대학원")
        mdis$V6<- recode_factor(mdis$V6, '1'="인문사회계열")
        mdis$V6<- recode_factor(mdis$V6, '2'="예체능계열")
        mdis$V6<- recode_factor(mdis$V6, '3'="사범계열")
        mdis$V6<- recode_factor(mdis$V6, '4'="기타(상농공수산계열)")
        mdis$V6<- recode_factor(mdis$V6, '5'="자연계열")
        mdis$V6<- recode_factor(mdis$V6, '6'="의약계열")
        mdis$V7<- recode_factor(mdis$V7, '1'="졸업")
        mdis$V7<- recode_factor(mdis$V7, '2'="재학")
        mdis$V7<- recode_factor(mdis$V7, '3'="중퇴")
        mdis$V7<- recode_factor(mdis$V7, '4'="휴학")
        mdis$V8<- recode_factor(mdis$V8, '1'="미혼")
        mdis$V8<- recode_factor(mdis$V8, '2'="유배우")
        mdis$V8<- recode_factor(mdis$V8, '3'="사별")
        mdis$V8<- recode_factor(mdis$V8, '4'="이혼")
        mdis$V9<- recode_factor(mdis$V9, '1'="일하였음")
        mdis$V9<- recode_factor(mdis$V9, '2'="일시휴직")
        mdis$V9<- recode_factor(mdis$V9, '3'="구직활동")
        mdis$V9<- recode_factor(mdis$V9, '4'="육아")
        mdis$V9<- recode_factor(mdis$V9, '5'="가사")
        mdis$V9<- recode_factor(mdis$V9, '6'="통학")
        mdis$V9<- recode_factor(mdis$V9, '7'="연로")
        mdis$V9<- recode_factor(mdis$V9, '8'="심신장애")
        mdis$V9<- recode_factor(mdis$V9, '9'="기타")
        mdis$V10<- recode_factor(mdis$V10, '1'="있었음")
        mdis$V10<- recode_factor(mdis$V10, '2'="무급가족종사자")
        mdis$V10<- recode_factor(mdis$V10, '3'="없었음")
        mdis$V11<- recode_factor(mdis$V11, '11'="일시적 병. 사고")
        mdis$V11<- recode_factor(mdis$V11, '12'="연가. 교육")
        mdis$V11<- recode_factor(mdis$V11, '13'="가족적이유")
        mdis$V11<- recode_factor(mdis$V11, '14'="노사분규")
        mdis$V11<- recode_factor(mdis$V11, '15'="조업중단")
        mdis$V11<- recode_factor(mdis$V11, '16'="기타")
        mdis$V11<- recode_factor(mdis$V11, '20'="없었음")
        mdis$V12<- recode_factor(mdis$V12, '1'="구해보았음")
        mdis$V12<- recode_factor(mdis$V12, '2'="구해보지 않았음")
        mdis$V13<- recode_factor(mdis$V13, '1'="구해보았음")
        mdis$V13<- recode_factor(mdis$V13, '2'="구해보지 않았음")
        mdis$V15<- recode_factor(mdis$V15, '1'="18시간미만 무급가족종사자")
        mdis$V15<- recode_factor(mdis$V15, '2'="1~35시간")
        mdis$V15<- recode_factor(mdis$V15, '3'="36시간이상")
        mdis$V16<- recode_factor(mdis$V16, '11'="정규근무시간36시간미만")
        mdis$V16<- recode_factor(mdis$V16, '12'="건강")
        mdis$V16<- recode_factor(mdis$V16, '13'="육아")
        mdis$V16<- recode_factor(mdis$V16, '14'="가사")
        mdis$V16<- recode_factor(mdis$V16, '15'="통학")
        mdis$V16<- recode_factor(mdis$V16, '16'="본인이원해서")
        mdis$V16<- recode_factor(mdis$V16, '17'="일거리없어서")
        mdis$V16<- recode_factor(mdis$V16, '18'="기타")
        mdis$V16<- recode_factor(mdis$V16, '21'="일시적병사고")
        mdis$V16<- recode_factor(mdis$V16, '22'="일기불순")
        mdis$V16<- recode_factor(mdis$V16, '23'="연가.교육")
        mdis$V16<- recode_factor(mdis$V16, '24'="육아")
        mdis$V16<- recode_factor(mdis$V16, '25'="가족적이유")
        mdis$V16<- recode_factor(mdis$V16, '26'="노사분규")
        mdis$V16<- recode_factor(mdis$V16, '27'="사업부진")
        mdis$V16<- recode_factor(mdis$V16, '28'="기타")
        mdis$V17<- recode_factor(mdis$V17, '1'="현재하고있는일의 시간 늘리고싶음")
        mdis$V17<- recode_factor(mdis$V17, '2'="현재하고있는일이외에 다른 일도 하고싶음")
        mdis$V17<- recode_factor(mdis$V17, '3'="더 많이 일할수있는일로 바꾸고싶음")
        mdis$V17<- recode_factor(mdis$V17, '4'="계속 그대로 일하고싶음")
        mdis$V18<- recode_factor(mdis$V18, '1'="있었음")
        mdis$V18<- recode_factor(mdis$V18, '2'="없었음")
        mdis$V19<- recode_factor(mdis$V19, '1'="직업소개소등록")
        mdis$V19<- recode_factor(mdis$V19, '2'="취직시험")
        mdis$V19<- recode_factor(mdis$V19, '3'="신문.잡지등 구직정보")
        mdis$V19<- recode_factor(mdis$V19, '4'="학교.학원 추천")
        mdis$V19<- recode_factor(mdis$V19, '5'="사업체 방문")
        mdis$V19<- recode_factor(mdis$V19, '6'="친구.친지 소개")
        mdis$V19<- recode_factor(mdis$V19, '7'="자영업준비")
        mdis$V19<- recode_factor(mdis$V19, '8'="기타(                  )")
        mdis$V21<- recode_factor(mdis$V21, '1'="임금근로")
        mdis$V21<- recode_factor(mdis$V21, '2'="비임금근로")
        mdis$V22<- recode_factor(mdis$V22, '1'="주로하는일")
        mdis$V22<- recode_factor(mdis$V22, '2'="틈틈이 하는일")
        mdis$V23<- recode_factor(mdis$V23, '1'="예")
        mdis$V23<- recode_factor(mdis$V23, '2'="아니오")
        mdis$V24<- recode_factor(mdis$V24, '1'="있었음")
        mdis$V24<- recode_factor(mdis$V24, '2'="없었음")
        mdis$V25<- recode_factor(mdis$V25, '1'="전공이나경력에 맞는일이 없을것 같아서")
        mdis$V25<- recode_factor(mdis$V25, '2'="원하는 임금수준이나 근로조건에 맞는 일이 없을것 같아서")
        mdis$V25<- recode_factor(mdis$V25, '3'="근처에 일거리가 없을것 같아서")
        mdis$V25<- recode_factor(mdis$V25, '4'="교육, 기술.경험부족해서")
        mdis$V25<- recode_factor(mdis$V25, '5'="나이가 너무어리거나 많다고 고용주가 생각할것 같아서")
        mdis$V25<- recode_factor(mdis$V25, '6'="이전에 찾아보았지만 일거리가 없어서")
        mdis$V25<- recode_factor(mdis$V25, '7'="육아.가사")
        mdis$V25<- recode_factor(mdis$V25, '8'="통학")
        mdis$V25<- recode_factor(mdis$V25, '9'="기타")
        mdis$V26<- recode_factor(mdis$V26, '1'="있었음")
        mdis$V26<- recode_factor(mdis$V26, '2'="없었음")
        mdis$V27<- recode_factor(mdis$V27, '1'="1년간 1회")
        mdis$V27<- recode_factor(mdis$V27, '2'="6개월간 1회")
        mdis$V27<- recode_factor(mdis$V27, '3'="3개월간 1회")
        mdis$V27<- recode_factor(mdis$V27, '4'="1개월간 1회")
        mdis$V27<- recode_factor(mdis$V27, '5'="1개월간 2~3회")
        mdis$V27<- recode_factor(mdis$V27, '6'="1개월간 4회이상")
        mdis$V28<- recode_factor(mdis$V28, '1'="1년미만")
        mdis$V28<- recode_factor(mdis$V28, '2'="1년이상 ~ 2년미만")
        mdis$V28<- recode_factor(mdis$V28, '3'="2년이상")
        mdis$V28<- recode_factor(mdis$V28, '4'="없었음")
        mdis$V30<- recode_factor(mdis$V30, '1'="개인.가족적이유")
        mdis$V30<- recode_factor(mdis$V30, '2'="건강상")
        mdis$V30<- recode_factor(mdis$V30, '3'="정년퇴직.연로")
        mdis$V30<- recode_factor(mdis$V30, '4'="작업여건불만족")
        mdis$V30<- recode_factor(mdis$V30, '5'="직장휴업.폐업")
        mdis$V30<- recode_factor(mdis$V30, '6'="명예.조기퇴직")
        mdis$V30<- recode_factor(mdis$V30, '7'="임시.계절적일의 완료")
        mdis$V30<- recode_factor(mdis$V30, '8'="일거리없어서, 또는 사업경영악화")
        mdis$V30<- recode_factor(mdis$V30, '9'="기타")
        mdis$V31<- recode_factor(mdis$V31, 'A'="농업 및 임업(01-02)")
        mdis$V31<- recode_factor(mdis$V31, 'B'="어 업(05)")
        mdis$V31<- recode_factor(mdis$V31, 'C'="광 업(10-14)")
        mdis$V31<- recode_factor(mdis$V31, 'D'="제 조 업(15-37)")
        mdis$V31<- recode_factor(mdis$V31, 'E'="전기, 가스 및 수도사업(40-41)")
        mdis$V31<- recode_factor(mdis$V31, 'F'="건설업(45)")
        mdis$V31<- recode_factor(mdis$V31, 'G'="도소매 및 소비자용품 수리업(50-52)")
        mdis$V31<- recode_factor(mdis$V31, 'H'="숙박 및 음식점업(55)")
        mdis$V31<- recode_factor(mdis$V31, 'I'="운수, 창고 및 통신업(60-64)")
        mdis$V31<- recode_factor(mdis$V31, 'J'="금융 및 보험업(65-67)")
        mdis$V31<- recode_factor(mdis$V31, 'K'="부동산업 및 임대업 및 사업서비스업(70-74)")
        mdis$V31<- recode_factor(mdis$V31, 'L'="공공행정, 국방 및 사회보장행정(75)")
        mdis$V31<- recode_factor(mdis$V31, 'M'="교육 서비스업(80)")
        mdis$V31<- recode_factor(mdis$V31, 'N'="보건 및 사회복지사업(85)")
        mdis$V31<- recode_factor(mdis$V31, 'O'="기타 공공, 사회 및 개인서비스업(90-93)")
        mdis$V31<- recode_factor(mdis$V31, 'P'="가사 서비스업(95)")
        mdis$V31<- recode_factor(mdis$V31, 'Q'="국제 및 외국기관(99)")
        mdis$V32<- recode_factor(mdis$V32, '1'="입법공무원,고위임직원 및 관리자")
        mdis$V32<- recode_factor(mdis$V32, '2'="전문가")
        mdis$V32<- recode_factor(mdis$V32, '3'="기술공 및 준전문가")
        mdis$V32<- recode_factor(mdis$V32, '4'="사무직원")
        mdis$V32<- recode_factor(mdis$V32, '5'="서비스근로자 및 상점과 시장판매 근로자")
        mdis$V32<- recode_factor(mdis$V32, '6'="농업 및 어업숙련 근로자")
        mdis$V32<- recode_factor(mdis$V32, '7'="기능원 및 관련 기능근로자")
        mdis$V32<- recode_factor(mdis$V32, '8'="장치, 기계조작원  및  조립원")
        mdis$V32<- recode_factor(mdis$V32, '9'="단순노무직 종사자")
        mdis$V33<- recode_factor(mdis$V33, '1'="상용근로자")
        mdis$V33<- recode_factor(mdis$V33, '2'="임시근로자")
        mdis$V33<- recode_factor(mdis$V33, '3'="일용근로자")
        mdis$V33<- recode_factor(mdis$V33, '4'="고용주")
        mdis$V33<- recode_factor(mdis$V33, '5'="자영자")
        mdis$V33<- recode_factor(mdis$V33, '6'="무급가족종사자")
        mdis$V34<- recode_factor(mdis$V34, '1'="1-4인")
        mdis$V34<- recode_factor(mdis$V34, '2'="5-9인")
        mdis$V34<- recode_factor(mdis$V34, '3'="10-29인")
        mdis$V34<- recode_factor(mdis$V34, '4'="30-99인")
        mdis$V34<- recode_factor(mdis$V34, '5'="100-299인")
        mdis$V34<- recode_factor(mdis$V34, '6'="300인 이상")
        mdis$V36<- recode_factor(mdis$V36, '1'="초졸이하")
        mdis$V36<- recode_factor(mdis$V36, '2'="중졸")
        mdis$V36<- recode_factor(mdis$V36, '3'="고졸")
        mdis$V36<- recode_factor(mdis$V36, '4'="초대졸")
        mdis$V36<- recode_factor(mdis$V36, '5'="대졸")
        mdis$V36<- recode_factor(mdis$V36, '6'="대학원졸")
        mdis$V37<- recode_factor(mdis$V37, '1'="농가")
        mdis$V37<- recode_factor(mdis$V37, '2'="비농가")
        mdis$V38<- recode_factor(mdis$V38, '1'="시부")
        mdis$V38<- recode_factor(mdis$V38, '2'="군부")
        mdis$V40<- recode_factor(mdis$V40, '01'="15~19세")
        mdis$V40<- recode_factor(mdis$V40, '02'="20~24세")
        mdis$V40<- recode_factor(mdis$V40, '03'="25~29세")
        mdis$V40<- recode_factor(mdis$V40, '04'="30~34세")
        mdis$V40<- recode_factor(mdis$V40, '05'="35~39세")
        mdis$V40<- recode_factor(mdis$V40, '06'="40~44세")
        mdis$V40<- recode_factor(mdis$V40, '07'="45~49세")
        mdis$V40<- recode_factor(mdis$V40, '08'="50~54세")
        mdis$V40<- recode_factor(mdis$V40, '09'="55~59세")
        mdis$V40<- recode_factor(mdis$V40, '10'="60~64세")
        mdis$V40<- recode_factor(mdis$V40, '11'="65세이상")
        mdis$V41<- recode_factor(mdis$V41, 'A'="농업 및 임업(01-02)")
        mdis$V41<- recode_factor(mdis$V41, 'B'="어 업(05)")
        mdis$V41<- recode_factor(mdis$V41, 'C'="광 업(10-12)")
        mdis$V41<- recode_factor(mdis$V41, 'D'="제 조 업(15-37)")
        mdis$V41<- recode_factor(mdis$V41, 'E'="전기, 가스 및 수도사업(40-41)")
        mdis$V41<- recode_factor(mdis$V41, 'F'="건설업(45)")
        mdis$V41<- recode_factor(mdis$V41, 'G'="도소매업(50-52)")
        mdis$V41<- recode_factor(mdis$V41, 'H'="숙박 및 음식점업(55)")
        mdis$V41<- recode_factor(mdis$V41, 'I'="운수업(60-63)")
        mdis$V41<- recode_factor(mdis$V41, 'J'="통신업(64)")
        mdis$V41<- recode_factor(mdis$V41, 'K'="금융 및 보험업(65-67)")
        mdis$V41<- recode_factor(mdis$V41, 'L'="부동산업 및 임대업(70-71)")
        mdis$V41<- recode_factor(mdis$V41, 'M'="사업서비스업(72-75)")
        mdis$V41<- recode_factor(mdis$V41, 'N'="공공행정, 국방 및 사회보장행정(76)")
        mdis$V41<- recode_factor(mdis$V41, 'O'="교육 서비스업(80)")
        mdis$V41<- recode_factor(mdis$V41, 'P'="보건 및 사회복지사업(85-86)")
        mdis$V41<- recode_factor(mdis$V41, 'Q'="오락, 문화 및 운동관련산업(87-88)")
        mdis$V41<- recode_factor(mdis$V41, 'R'="기타 공공, 수리 및 개인서비스업(90-93)")
        mdis$V41<- recode_factor(mdis$V41, 'S'="가사 서비스업(95)")
        mdis$V41<- recode_factor(mdis$V41, 'T'="국제 및 외국기관(99)")
        mdis$V42<- recode_factor(mdis$V42, '0'="의회의원, 고위임직원 및 관리자")
        mdis$V42<- recode_factor(mdis$V42, '1'="전문가")
        mdis$V42<- recode_factor(mdis$V42, '2'="기술공 및 준전문가")
        mdis$V42<- recode_factor(mdis$V42, '3'="사무 종사자")
        mdis$V42<- recode_factor(mdis$V42, '4'="서비스 종사자")
        mdis$V42<- recode_factor(mdis$V42, '5'="판매 종사자")
        mdis$V42<- recode_factor(mdis$V42, '6'="농업, 임업 및 어업 숙련 종사자")
        mdis$V42<- recode_factor(mdis$V42, '7'="기능원 및 관련 기능 종사자")
        mdis$V42<- recode_factor(mdis$V42, '8'="장치, 기계조작 및  조립 종사자")
        mdis$V42<- recode_factor(mdis$V42, '9'="단순노무 종사자")
        mdis$V43<- recode_factor(mdis$V43, '1'="취업자")
        mdis$V43<- recode_factor(mdis$V43, '2'="실업자")
        mdis$V43<- recode_factor(mdis$V43, '3'="비경제활동인구")

colnames(mdis) = c("조사연월"
, "가구주관계코드", "성별코드", "출생연도", "교육정도_학력구분코드", "교육정도_계열코드", "교육정도_수학구분코드", "혼인상태코드", "기타활동사항_지난주주요활동상태코드", "현재일관련사항_지난주수입목적근로여부", "현재일관련사항_지난주일시휴직여부", "취업판단항목_1주간구직여부", "구직사항_지난4주내구직여부", "현재일관련사항_총실제취업시간수", "현재일관련사항_지난주총근로시간구분코드", "현재일관련사항_평소1주간36시간미만근무사유코드", "현재일관련사항_추가취업전직희망코드", "구직사항_취업가능성유무", "구직사항_주요구직방법1코드", "구직사항_구직활동기간", "구직사항_희망고용형태코드"
, "구직사항_희망근무형태코드", "비경제활동구직의사여부", "비경제활동취업가능성유무", "기타활동사항_4주내비구직사유코드", "기타활동사항_지난1년내구직활동유무", "구직활동기간별_구직활동횟수구분코드", "이전직장사항_전직유무", "이전직장사항_1년미만퇴직연월", "이전직장사항_이직사유코드", "현재일관련사항_7차산업대분류코드", "현재일관련사항_4차직업대분류코드", "현재일관련사항_종사상지위코드", "현재일관련사항_종사자규모코드", "가중값", "교육정도컨버젼코드", "농가비농가가구구분코드", "동부읍면부코드", "만연령", "연령5세단위코드", "현재일관련사항_8차산업대분류코드"
, "현재일관련사항_5차직업대분류코드", "경제활동상태코드")

